
import { 
    EFFECTS, STYLES, LAYOUTS, BORDERS, ACCESSORIES, HANDHELD_ITEMS, 
    PETS, TET_BACKGROUNDS, TET_OUTFITS_FEMALE, TET_OUTFITS_MALE, 
    FLOWERS, DESTINATIONS, FAMILY_CONCEPTS, TRAVEL_CONCEPTS, CAMERA_ANGLES,
    TET_WISHES, STUDIO_CONCEPTS, CALENDAR_CONCEPTS, ROYAL_CONCEPTS, 
    EMERALD_CONCEPTS, BILLIONAIRE_CONCEPTS, HEAVENLY_CONCEPTS, ZODIAC_HORSE_CONCEPTS,
    PHOENIX_CONCEPTS, FASHION_STUDIO_CONCEPTS, FAMILY_STUDIO_VIP_CONCEPTS, 
    FLOWER_SPRING_CONCEPTS, PAGODA_LUCK_CONCEPTS, // Imported NEW
    FEMALE_POSES_VIP, 
    MALE_POSES_VIP, 
    CALENDAR_WEEKDAYS, CALENDAR_DAYS, CALENDAR_MONTHS, CALENDAR_YEARS,
    CALENDAR_TYPES, 
    VIP_QUOTES 
} from "./components/constants_data";

export const ASPECT_RATIOS = ['9:16 📱', '1:1 🖼️', '16:9 💻'];
export const IMAGE_COUNTS = ['1 Ảnh 🧧', '2 Ảnh 🧧🧧', '3 Ảnh 🧧🧧🧧'];

export { 
    EFFECTS, STYLES, LAYOUTS, BORDERS, ACCESSORIES, HANDHELD_ITEMS, 
    PETS, TET_BACKGROUNDS, TET_OUTFITS_FEMALE, TET_OUTFITS_MALE, 
    FLOWERS, DESTINATIONS, FAMILY_CONCEPTS, TRAVEL_CONCEPTS, CAMERA_ANGLES,
    TET_WISHES, STUDIO_CONCEPTS, CALENDAR_CONCEPTS, ROYAL_CONCEPTS, 
    EMERALD_CONCEPTS, BILLIONAIRE_CONCEPTS, HEAVENLY_CONCEPTS, ZODIAC_HORSE_CONCEPTS,
    PHOENIX_CONCEPTS, FASHION_STUDIO_CONCEPTS, FAMILY_STUDIO_VIP_CONCEPTS,
    FLOWER_SPRING_CONCEPTS, PAGODA_LUCK_CONCEPTS, // Export NEW
    FEMALE_POSES_VIP, 
    MALE_POSES_VIP, 
    CALENDAR_WEEKDAYS, CALENDAR_DAYS, CALENDAR_MONTHS, CALENDAR_YEARS,
    CALENDAR_TYPES, 
    VIP_QUOTES 
};
