
// ... (previous content remains the same until CALENDAR_CONCEPTS)

export const TET_WISHES = [
    'VẠN SỰ NHƯ Ý',
    'TẤN TÀI TẤN LỘC',
    'AN KHANG THỊNH VƯỢNG',
    'CUNG CHÚC TÂN XUÂN',
    'XUÂN NHƯ Ý - TẾT AN KHANG',
    'TÀI LỘC ĐẦY NHÀ',
    'PHÚ QUÝ VINH HOA',
    'GIA ĐẠO BÌNH AN',
    'ĐẮC LỘC TOÀN GIA',
    'PHÚC LỘC THỌ TOÀN',
    'KHAI XUÂN ĐẠI CÁT',
    'MÃ ĐÁO THÀNH CÔNG',
    'XUÂN SANG ĐẮC LỘC',
    'TẾT ĐẾN AN VUI',
    'HẠNH PHÚC NGẬP TRÀN',
    'SỨC KHỎE DỒI DÀO',
    'LỘC BIẾC MAI VÀNG',
    'XUÂN AN KHANG',
    'TẾT SUM VẦY',
    'ĐẠI PHÚ ĐẠI QUÝ'
];

export const VIP_QUOTES = [
    "Tết đến rồi, đẹp lên thôi!",
    "Năm mới – diện mới – khí chất mới.",
    "Tết này em chọn… xinh xuất sắc.",
    "Tết không cần nhiều, chỉ cần ĐẸP.",
    "Xuân sang rồi, bung sắc liền!",
    "Tết có đôi, còn em có… ảnh đẹp.",
    "Lì xì đâu chưa thấy, chỉ thấy em hơi đẹp.",
    "Tết chill – em rực rỡ.",
    "Xuân này em hứa: ĐẸP ĐẾN PHÁT MÊ.",
    "Tết này icon chính là em.",
    "Mã đáo thành công rực rỡ",
    "Ngựa vàng mang lộc đầu năm",
    "Phi nhanh mở cửa thắng lớn",
    "Chiến mã bứt phá cả năm",
    "Mã khí thịnh vượng bùng nổ",
    "Cưỡi gió phi thẳng thành công",
    "Ngựa thần mở vận đại cát",
    "Tốc độ bùng nổ như ngựa",
    "Vận may phi nước đại tới",
    "Tiền tài tuôn như ngựa chạy"
];

// --- 100 POSES FOR FEMALE VIP ---
export const FEMALE_POSES_VIP = [
    // 1–25: KẾT HỢP ĐỨNG + TAY + CẢM XÚC
    "Đứng nghiêng 45° + tay che miệng + cười cute.",
    "Đứng xoay người + tay đưa ngang má + mắt nhắm nhẹ.",
    "Đứng vắt chân + hai tay tạo trái tim + nụ cười kute.",
    "Đứng pose chữ S + tay vuốt tóc + ánh mắt sexy.",
    "Hai tay chống hông + mắt nháy nhẹ + miệng cong gợi cảm.",
    "Đứng một chân nhón + tay che nắng + cười rạng rỡ.",
    "Đứng tạo dáng idol + tay chữ V + môi chu siêu dễ thương.",
    "Hai tay khoanh + ánh mắt quyến rũ lạnh lùng.",
    "Đứng chống cằm + body nghiêng + vibe shy girl.",
    "Đứng cắn môi + tay kéo áo nhẹ + vibe sexy.",
    "Một tay chống hông + tay còn lại đưa lên tóc + mắt nhìn lệch.",
    "Đứng xoay lưng + xoay đầu lại + biểu cảm gợi cảm.",
    "Đứng cúi đầu nhẹ + tay chạm môi + ánh mắt sâu.",
    "Đứng dang tay xoay váy + mặt cười tỏa nắng.",
    "Đứng kiểu model + tay cài tóc + gương mặt confident.",
    "Đứng kẹp tay áo + biểu cảm cute ngại ngùng.",
    "Đứng nhướn chân + tay nắm cổ áo + môi cong nhẹ.",
    "Đứng dựa tường + tay bỏ túi + ánh mắt quyến rũ.",
    "Tay chống lưng + ngực hơi đưa ra + pose sexy.",
    "Một tay giơ lên trời + một tay để hông + cười tinh nghịch.",
    "Đứng tay dang sang hai bên + mắt nhắm + vibe thiên thần.",
    "Đứng một chân co + tay chống cằm + cute.",
    "Đứng ôm gối chữ O bằng tay + môi cong dễ thương.",
    "Đứng kéo tóc hai bên + ánh mắt mèo con.",
    "Đứng xoay váy + chân chéo + tay dang nhẹ.",

    // 26–50: KẾT HỢP NGỒI + TAY CHÂN + CẢM XÚC
    "Ngồi bó gối + hai tay ôm chân + cười như trẻ con.",
    "Ngồi vắt chân + tay chống má + biểu cảm sexy nhẹ.",
    "Ngồi xoay người 45° + tay vuốt tóc + nhìn lệch quyến rũ.",
    "Ngồi ôm gối một tay + tay còn lại che miệng cute.",
    "Ngồi trên sàn + hai chân mở nhẹ + ánh mắt seductive.",
    "Ngồi tựa tường + tay ôm đầu gối + gương mặt shy girl.",
    "Ngồi dạng chân nhẹ + hai tay chống sau + ánh mắt tự tin.",
    "Ngồi trên ghế + một chân đặt cao + pose fashion.",
    "Ngồi dựa lưng + tay kéo tóc + môi cong.",
    "Ngồi tư thế “nàng thơ” + tay đặt hờ lên cổ.",
    "Ngồi bệt + tay chống xuống đất + mắt cười.",
    "Ngồi chéo chân + tay ôm gối + gương mặt đáng yêu.",
    "Ngồi xoay chèo người + tay vuốt đùi + sexy vibe.",
    "Ngồi ôm gối + cười nháy mắt siêu cute.",
    "Ngồi trên ghế xoay lưng ra trước + tay ôm khung ghế.",
    "Ngồi kiểu model runway + chân dài duỗi ra.",
    "Ngồi nghiêng + tay chống thái dương + mắt xa xăm.",
    "Ngồi kéo váy nhẹ + tay đặt lên đùi + vibe hấp dẫn.",
    "Ngồi chống cằm + mái tóc rơi sang một bên.",
    "Ngồi ngửa đầu ra sau + tay đặt lên cổ.",
    "Ngồi gập người ôm chân + nụ cười hạnh phúc.",
    "Ngồi xoay váy trên sàn + tay đưa ra trước.",
    "Ngồi pose yoga nhẹ + cười hiền.",
    "Ngồi nháy mắt + tay hình trái tim.",
    "Ngồi ôm chân + toàn thân nghiêng sexy.",

    // 51–75: KẾT HỢP NẰM + XOAY + BIỂU CẢM
    "Nằm nghiêng chống đầu + cười nhẹ.",
    "Nằm ngửa + tay đặt lên môi + ánh mắt long lanh.",
    "Nằm úp + xoay đầu + tóc xoã.",
    "Nằm ôm gối + môi chu cute.",
    "Nằm chống 1 khủy tay + pose sexy.",
    "Nằm nghiêng chân duỗi dài + tay đặt hờ lên eo.",
    "Nằm tạo dáng chữ S + mắt nhìn camera.",
    "Nằm nâng đầu + tay vuốt tóc + vibe tiểu thư.",
    "Nằm xoay lưng + đầu hòa vào tóc xoã.",
    "Nằm cuộn tròn như mèo + ánh mắt dễ thương.",
    "Nằm pose fashion editorial + đầu hơi vươn cao.",
    "Nằm ôm chăn + ánh mắt gợi tình.",
    "Nằm dạng tay hai bên + môi cong quyến rũ.",
    "Nằm nhắm mắt + tóc xõa + vibe công chúa.",
    "Nằm xoay chân nhẹ + tay đặt lên vai.",
    "Nằm úp 1 phần + ánh mắt muốn yêu.",
    "Nằm nghiêng đầu + tay che nửa mặt + sexy.",
    "Nằm quay đầu ra sau + tóc bung xoãi.",
    "Nằm pose dạng model tạp chí.",
    "Nằm tay ôm ngực + mắt sâu tình.",

    // 76–100: TƯ THẾ KHÓ + SEXY + NGHỆ THUẬT
    "Uốn cong người + tay đặt lên đùi + mắt quyến rũ.",
    "Tư thế dancer xoay người + tóc bung 8D.",
    "Nhảy giữa không trung + cười cute.",
    "Xoạc nhẹ + tay che mặt + ánh mắt gợi cảm.",
    "Tư thế bẻ lưng mềm dẻo + đôi tay dang.",
    "Chống 1 tay trên sàn + chân co + ánh mắt deep.",
    "Tư thế xoay váy tốc độ + nụ cười sáng.",
    "Pose yoga khó + tóc xoã gợi cảm.",
    "Tư thế fashion high-level + môi cong.",
    "Một chân nâng cao + tay chạm cổ + sexy.",
    "Tư thế quỳ gối + tay vuốt tóc + ánh mắt seductive.",
    "Tư thế quỳ + chống tay + lưng hơi cong.",
    "Tư thế ngồi squat + cười cute.",
    "Tư thế xoay hông kiểu dancer.",
    "Tư thế pose “thiên thần” dang tay.",
    "Tư thế hair flip – tung tóc.",
    "Tư thế quỳ gối fashion editorial.",
    "Tư thế nằm nửa người uốn cong.",
    "Tư thế tạo đường cong cơ thể chữ S.",
    "Tư thế duỗi chân dài + tay nâng cằm.",
    "Tư thế quỳ quay lưng + xoay đầu lại.",
    "Tư thế uốn lưng cầu vồng + ánh mắt sexy.",
    "Pose xoay hình chữ V bằng tay.",
    "Tư thế gập người nửa thân + mắt nhìn camera.",
    "Tư thế xoay chân phức tạp + tay vuốt tóc + biểu cảm quyến rũ."
];

// --- 100 POSES FOR MALE VIP ---
export const MALE_POSES_VIP = [
    // 1–30: TƯ THẾ ĐỨNG – QUYỀN LỰC – LỊCH LÃM – DOANH NHÂN TỶ ĐÔ
    "Đứng thẳng vai rộng + tay đút túi + nhìn xa phong độ.",
    "Đứng khoanh tay + ánh mắt sắc lạnh CEO.",
    "Đứng chống hông + hơi nghiêng người đầy tự tin.",
    "Đứng dựa tường + tay vuốt tóc + ánh mắt quyến rũ.",
    "Đứng thẳng + một tay kéo cổ áo vest.",
    "Đứng bắt chéo chân + tay cài khuy áo.",
    "Đứng xoay người 45° + nhìn qua vai đỉnh cao.",
    "Đứng bỏ một tay trong túi quần + tay còn lại cầm kính.",
    "Đứng cắn môi nhẹ + ánh mắt deep.",
    "Đứng kẹp áo khoác lên vai + thần thái doanh nhân.",
    "Đứng với hai tay chống sau lưng + khí chất quý ông.",
    "Đứng tay cầm điện thoại nhìn xuống sang trọng.",
    "Đứng tay kẹp cà vạt + thần thái điển trai.",
    "Đứng chống tay lên tường + nhìn sát camera.",
    "Đứng nhìn xuống đất + biểu cảm lạnh lùng.",
    "Đứng một chân nhón nhẹ + tay chống cằm deep.",
    "Đứng xoay đầu qua bên + hai tay thả lỏng.",
    "Đứng khoanh tay trước ngực + ánh mắt quyền lực.",
    "Đứng dang nhẹ hai chân + dáng phong độ.",
    "Đứng dạng chân mạnh mẽ + ánh mắt “alpha male”.",
    "Đứng hai tay bỏ hai túi + dáng relaxed luxury.",
    "Đứng cầm áo vest trên vai + nụ cười nhẹ.",
    "Đứng hai tay chống hông + camera low-angle.",
    "Đứng dang 1 tay ra sau + nụ cười phong trần.",
    "Đứng xoay người + cầm ly rượu vang sang trọng.",
    "Đứng một tay chống tường + ánh mắt quyến rũ.",
    "Đứng gập người buộc dây giày + góc nghiêng đẹp trai.",
    "Đứng hai tay nắm cổ áo + ánh mắt self-made billionaire.",
    "Đứng giơ một tay lên trời + khí chất vĩ mô.",
    "Đứng nghiêng + túm tay áo sơ mi đang xắn.",

    // 31–60: TƯ THẾ NGỒI – SANG – PHONG ĐỘ – QUYỀN LỰC
    "Ngồi thẳng lưng + khoanh tay + ánh mắt quyền lực.",
    "Ngồi bắt chéo chân + tay đặt lên đùi.",
    "Ngồi nghiêng 45° + tay chống cằm thoughtful.",
    "Ngồi trên sofa + tay khoác lên lưng ghế.",
    "Ngồi cúi đầu + xắn tay áo sơ mi mạnh mẽ.",
    "Ngồi xoay người + tay giữ cổ áo vest.",
    "Ngồi chống 1 tay lên bàn + ánh mắt lạnh.",
    "Ngồi chân mở nhẹ + tay thả lỏng.",
    "Ngồi với 1 chân bắt chéo lên gối + nét quý ông.",
    "Ngồi ngả người ra sau tự tin.",
    "Ngồi kiểu CEO, tay đan vào nhau.",
    "Ngồi cúi mặt + đeo kính + ánh sáng mạnh.",
    "Ngồi một chân co, một chân duỗi + thần thái lịch lãm.",
    "Ngồi kiểu fashion model high-end.",
    "Ngồi với tay vuốt tóc + ánh mắt sexy.",
    "Ngồi xoay ghế ngược + tay đặt lên lưng ghế.",
    "Ngồi tựa đầu vào tay + nụ cười nửa miệng.",
    "Ngồi chống 2 tay lên bàn + thần thái tập trung.",
    "Ngồi xoay mặt ra ánh sáng + đôi mắt sâu.",
    "Ngồi gác chân lên ghế + dáng nghệ sĩ giàu sang.",
    "Ngồi vắt chân + tay cầm ly cà phê sang trọng.",
    "Ngồi khoanh tay – chân mở – CEO.",
    "Ngồi xoay vai ra sau + khí chất quý ông lạnh lùng.",
    "Ngồi tư thế thư giãn + ánh mắt lãng tử.",
    "Ngồi cúi nhẹ người về phía camera.",
    "Ngồi gập người cột dây giày + dáng menly.",
    "Ngồi pose studio + ánh sáng bóng đổ đẹp.",
    "Ngồi với áo khoác đặt trên vai.",
    "Ngồi ghế cao bar + xoay vai qua lại.",
    "Ngồi kết hợp mặt lạnh + đôi môi cong nhẹ.",

    // 61–80: TƯ THẾ NẰM – PHONG LƯU – LỊCH LÃM – QUYẾN RŨ
    "Nằm nghiêng + tay chống đầu + mắt nhìn xa.",
    "Nằm úp nhẹ + xoay đầu nhìn camera.",
    "Nằm ngửa + tay đặt lên ngực + ánh mắt deep.",
    "Nằm co 1 chân + gương mặt thư thái.",
    "Nằm hơi xoay người + tay vuốt tóc.",
    "Nằm nghiêng + ánh mắt quyến rũ kiểu điện ảnh.",
    "Nằm fashion editorial – tạo đường cong nam tính.",
    "Nằm ở sofa + tay để sau đầu + pose relaxed luxury.",
    "Nằm tay ôm gối + biểu cảm suy tư.",
    "Nằm xoay đầu + tay chạm môi nhẹ.",
    "Nằm pose “bad boy” với ánh mắt sấm sét.",
    "Nằm dang 2 tay + mắt nhìn trần – deep mood.",
    "Nằm 1 tay trước bụng + dáng phong trần.",
    "Nằm nghiêng kiểu người mẫu nước ngoài.",
    "Nằm dạng rộng + nhìn mạnh mẽ.",
    "Nằm đọc sách + góc nghiêng thần thánh.",
    "Nằm trên bãi cỏ + tay che nắng.",
    "Nằm ngả người + tay cầm điện thoại luxury.",
    "Nằm mắt nhắm + tóc hơi rũ.",
    "Nằm sấp nhẹ + cơ thể lộ đường nét nam tính.",

    // 81–100: TƯ THẾ KHÓ – HIGH-FASHION – SIÊU ĐẲNG CẤP
    "Tư thế xoay người mạnh + tóc bay.",
    "Quỳ 1 chân + tay chống đầu gối + ánh mắt lãnh đạm.",
    "Nhảy nhẹ mid-air + camera freeze.",
    "Cúi người 90° + pose fashion runway.",
    "Xoay cổ tay + mặt nghiêng + ánh mắt sắc.",
    "Chống 1 tay lên tường + chân dạng chuẩn model.",
    "Đang đeo đồng hồ + pose góc sang.",
    "Uốn lưng nhẹ + ánh sáng rọi một bên.",
    "Ngửa đầu ra sau + tay nắm cổ áo.",
    "Pose đường cong chữ S phiên bản nam.",
    "Bước đi mạnh mẽ + tay đưa ra sau. ",
    "Quay đầu nhìn lại khi đang bước.",
    "Một tay đưa lên trán + ánh mắt deep mysterious.",
    "Tay cầm áo vest tung nhẹ ra sau.",
    "Dang tay kiểu artist high-class.",
    "Bước chân dài kiểu model quốc tế.",
    "Tư thế đứng lùi + gương mặt lạnh lùng.",
    "Ngồi quỳ thấp + tay chống sàn + ánh mắt sắc.",
    "Tư thế fashion editorial kiểu GQ Men.",
    "Tư thế xoay mình kết hợp áo bay + khí chất siêu cấp."
];

export const CALENDAR_TYPES = [
    '📅 Lịch Tờ Từng Tháng (Layout 1 Tháng - Focus Chi Tiết)',
    '📆 Lịch Nguyên Năm (Full Year Poster - Overview)',
    '📒 Lịch Để Bàn (Desk Calendar - Office Style)',
    '📜 Lịch Bloc Treo Tường (Traditional Bloc)',
    '📱 Hình Nền Điện Thoại (Lockscreen Calendar)'
];

// --- CLEANED UP YEAR LIST: ONLY 2026 AS REQUESTED ---
export const CALENDAR_YEARS = [
    'Năm 2026 (Bính Ngọ)'
];

// --- UPDATED CALENDAR CONCEPTS (VIP LIST) ---
export const CALENDAR_CONCEPTS = [
    '📅 1. Lịch Sang Trọng Đen – Gold Modern Luxury',
    '📅 2. Lịch City Luxury – Doanh Nhân Tỷ Đô',
    '📅 3. Lịch Tết Cổ Điển Sang – Gỗ & Gold',
    '📅 4. Lịch Minimal Đỉnh Cao – Vàng Trắng 8K',
    '📅 5. Lịch Studio 8K – Lụa Vàng Bay Cao Cấp',
    '📅 6. Lịch Neon Gold Future – Công Nghệ',
    '📅 7. Lịch Richlife – Vàng & Trắng Cao Cấp',
    '📅 8. Lịch Ngọ Vàng – Premium Metallic',
    '📅 9. Lịch Fashion Tết – Sàn Diễn Cao Cấp',
    '📅 10. Lịch Tết Nghệ Thuật – Background 3D',
    '📅 11. Lịch Grid 4x3 (12 Ô Siêu Chuẩn)',
    '📅 12. Lịch Grid 3x4 (Ngang Rộng)',
    '📅 13. Lịch 12 Tháng Ngang (1 Hàng Dài)',
    '📅 14. Lịch 2 Hàng (Cân Đối Hoàn Hảo)',
    '📅 15. Lịch 12 Card Mini (Premium)',
    '📅 16. Lịch Hình Tròn (Hiện Đại)',
    '📅 17. Lịch Block Truyền Thống (Đỏ Vàng)',
    '📅 18. Lịch Thanh Bar Mảnh (Siêu Hiện Đại)',
    '📅 19. Lịch 3D Nổi (Sắc Xảo Đẳng Cấp)',
    '📅 20. Lịch Đồng Tâm (12 Cung Tròn)'
];

export const PHOENIX_CONCEPTS = [
    '🔥 Phượng Hoàng Tái Sinh (Resurrection Phoenix - Ash & Fire)',
    '🔥 Nữ Hoàng Lửa Thiêng (Fire Queen - Flaming Crown)',
    '🔥 Vũ Khúc Lửa Thần (Fire Dance - Burning Fans)',
    '🔥 Cung Điện Mặt Trời (Sun Palace - Gold & Fire)',
    '🔥 Chiến Binh Phượng Hoàng (Phoenix Warrior - Gold Armor)',
    '🔥 Lễ Hội Lửa Thiêng (Sacred Fire Festival - Lanterns)',
    '🔥 Cổng Trời Rực Lửa (Burning Heaven Gate)',
    '🔥 Phượng Hoàng Song Sinh (Twin Phoenix - Symmetry)',
    '🔥 Ngai Vàng Lửa Đỏ (Throne of Fire - Power)',
    '🔥 Thảm Đỏ Hoàng Gia (Royal Red Carpet - Gold Confetti)',
    '🔥 Đôi Cánh Lửa Neon (Neon Fire Wings - Cyberpunk)',
    '🔥 Trứng Phượng Hoàng (Phoenix Egg - Glowing)',
    '🔥 Hoa Đăng Lửa (Floating Fire Lanterns)',
    '🔥 Kim Thân Bất Hoại (Golden Skin - Immortal)',
    '🔥 Mắt Phượng Hoàng (Phoenix Eye Makeup)',
    '🔥 Lụa Đỏ Cháy (Burning Silk - Flowing)',
    '🔥 Hoa Ưu Đàm Lửa (Fire Udumbara Flower)',
    '🔥 Thần Mặt Trời (Sun God - Godrays)',
    '🔥 Hỏa Diệm Sơn (Volcano Aesthetic - Magma)',
    '🔥 Vòng Tròn Lửa Magic (Magic Fire Circle)',
    '🔥 Phượng Hoàng Băng Lửa (Ice & Fire Contrast)',
    '🔥 Cây Cổ Thụ Lửa (Burning Tree - Golden Leaves)',
    '🔥 Mưa Tàn Tro Vàng (Golden Ash Rain)',
    '🔥 Xích Đu Lửa (Swing in Fire Ocean)',
    '🔥 Cầu Lửa Bắc Ngang Trời (Fire Bridge)',
    '🔥 Lồng Đèn Kéo Quân Lửa (Spinning Lantern)',
    '🔥 Trống Trận Rực Lửa (Burning War Drums)',
    '🔥 Quạt Giấy Khổng Lồ (Giant Phoenix Fan)',
    '🔥 Phượng Hoàng Gấm Vóc (Embroidered Phoenix)',
    '🔥 Tiên Nữ Hỏa Cung (Fire Fairy)',
    '🔥 Hoàng Tử Lửa (Prince of Fire)',
    '🔥 Bếp Lửa Thần (Magical Kitchen Fire)',
    '🔥 Lân Sư Rồng Lửa (Fire Lion Dance)',
    '🔥 Mặt Nạ Phượng Hoàng (Phoenix Mask)',
    '🔥 Cung Tên Lửa (Fire Bow & Arrow)',
    '🔥 Đàn Tỳ Bà Lửa (Burning Pipa)',
    '🔥 Hồ Sen Lửa (Red Lotus Fire)',
    '🔥 Kim Tự Tháp Lửa (Fire Pyramid)',
    '🔥 Sao Hỏa Tết (Mars Tet Celebration)',
    '🔥 Dây Pháo Khổng Lồ (Giant Firecracker)',
    '🔥 Thư Pháp Lửa (Fire Calligraphy)',
    '🔥 Rượu Vang Lửa (Flaming Wine)',
    '🔥 Nhẫn Phượng Hoàng (Phoenix Ring Prop)',
    '🔥 Vườn Hồng Lửa (Burning Roses)',
    '🔥 Kim Cương Đỏ (Red Diamond Rain)',
    '🔥 Lụa Tân Cương (Xinjiang Fire Dance)',
    '🔥 Phượng Hoàng Origami (Paper Phoenix)',
    '🔥 Gương Thần Lửa (Fire Mirror)',
    '🔥 Bánh Xe Lửa (Wheel of Fire)',
    '🔥 Pháo Hoa Đại Cảnh (Grand Firework Display)'
];

// ... (rest of the file remains the same)