
// ... (Keep existing arrays: STYLES, LAYOUTS, BORDERS, ACCESSORIES, PETS, TET_BACKGROUNDS, TET_OUTFITS_FEMALE, TET_OUTFITS_MALE, FLOWERS, DESTINATIONS, FAMILY_CONCEPTS, TRAVEL_CONCEPTS, CAMERA_ANGLES, STUDIO_CONCEPTS, ROYAL_CONCEPTS, EMERALD_CONCEPTS, BILLIONAIRE_CONCEPTS, HEAVENLY_CONCEPTS, ZODIAC_HORSE_CONCEPTS, PHOENIX_CONCEPTS, FASHION_STUDIO_CONCEPTS, FAMILY_STUDIO_VIP_CONCEPTS, CALENDAR_WEEKDAYS, CALENDAR_DAYS, CALENDAR_MONTHS, CALENDAR_YEARS, CALENDAR_CONCEPTS, TET_WISHES, VIP_QUOTES, FEMALE_POSES_VIP, MALE_POSES_VIP, CALENDAR_TYPES, FLOWER_SPRING_CONCEPTS, PAGODA_LUCK_CONCEPTS)

export const EFFECTS = [
    // --- 20 NEW MAGICAL TET EFFECTS (LION DANCE / GOD OF WEALTH) ---
    '🦁 Múa Lân Sư Rồng 8K (Lion Dance Ultra)',
    '🦁 Đầu Lân Kim Cương (Diamond Lion Head) Lấp Lánh',
    '👴 Ông Địa Vẫy Quạt (Earth God Smile) Ban Phước',
    '💰 Thần Tài Gõ Cửa (God of Wealth Arrival) Vàng Rơi',
    '🐉 Rồng Vàng Nhả Ngọc (Golden Dragon Pearl) Huyền Bí',
    '🐉 Rồng Lửa Bay Lượn (Fire Dragon) Quấn Quanh',
    '🐉 Rồng Nước Cuộn Trào (Water Dragon) Uy Lực',
    '✨ Hào Quang Thần Tài (Wealth Aura) Tỏa Sáng',
    '🏮 Lồng Đèn Cá Chép Hóa Rồng (Carp Lantern) Bay',
    '🥁 Trống Hội Múa Lân (Drum Festival Vibes) Sôi Động',
    '🧧 Mưa Bao Lì Xì (Red Envelope Rain) Ngập Trời',
    '🐲 Tứ Linh Hội Tụ (Long Lân Quy Phụng) Linh Thiêng',
    '🎭 Mặt Nạ Ông Địa Cười (Happy Mask) Dễ Thương',
    '✨ Phép Thuật Biến Hình Tết (Magical Transformation)',
    '🎆 Pháo Hoa Hình Rồng (Dragon Fireworks) Rực Rỡ',
    '🌸 Cây Nêu Ngày Tết Phát Sáng (Glowing Neu Tree)',
    '📜 Chiếu Chỉ Vua Ban (Royal Scroll Effect) Bay',
    '🏵️ Mâm Ngũ Quả Bay (Floating Fruit Tray) Phép Thuật',
    '🪙 Tiền Xu Vàng Rơi (Falling Gold Coins) 3D',
    '✨ Bụi Tiên Táo Quân (Kitchen God Dust) Lấp Lánh',

    // --- 50+ SUPER VIP PRO TET EFFECTS (EXISTING) ---
    '✨ Phượng Hoàng Lửa Tái Sinh (Phoenix Reborn)',
    '🐉 Rồng Thần Vô Cực Phun Châu Nhả Ngọc',
    '💎 Mưa Kim Cương 8K & Hoa Mai Vàng',
    '🌌 Cổng Thời Gian Đón Giao Thừa',
    '🌸 Cây Đào Tiên 3000 Năm Rực Rỡ',
    '✨ Hào Quang Phật Pháp Nhiệm Màu Ngày Tết',
    '🎆 Pháo Hoa Đại Cảnh Paris Đón Tết',
    '👑 Vương Miện Ánh Sáng Nữ Thần Xuân',
    '🧚‍♀️ Cánh Tiên Tinkerbell Du Xuân',
    '🌪️ Lốc Xoáy Bụi Vàng Tài Lộc',
    '🌊 Sóng Thần Tài Lộc Cuộn Trào',
    '❄️ Tuyết Rơi Trên Cành Đào Đỏ',
    '🔥 Vòng Tròn Lửa Thiêng Đêm Trừ Tịch',
    '⚡ Sấm Sét Thor Đánh Thức Mùa Xuân',
    '🏮 Đèn Lồng Bay Kín Trời Đêm 30',
    '✨ Bụi Vàng 24K Rơi Lấp Lánh',
    '🌫️ Sương Mù Sapa Sáng Mùng 1',
    '🌈 Cầu Vồng Đôi May Mắn Đầu Năm',
    '🌠 Mưa Sao Băng Chúc Phúc',
    '🔮 Quả Cầu Pha Lê Tiên Tri Vận Mệnh',
    '✨ Vàng Rơi Lấp Lánh (Gold Dust)',
    '🎇 Pháo Hoa Rực Rỡ (Fireworks)',
    '🌸 Hoa Đào Rơi (Falling Peach Blossoms)',
    '🌫️ Sương Khói Mờ Ảo (Mystic Fog)',
    '☀️ Nắng Xuân Ấm Áp (Spring Sunlight)',
    '🏮 Đèn Lồng Bay (Flying Lanterns)',
    '💫 Hào Quang Thần Tiên (Divine Aura)',
    '🔥 Lửa Trại Nấu Bánh Chưng Ấm Cúng',
    '❄️ Tuyết Rơi Lãng Mạn (Romantic Snow)',
    '🌈 Cầu Vồng Rực Rỡ (Rainbow)',
    '✨ Bụi Tiên Tinkerbell',
    '✨ Ánh Sáng Neon Cyberpunk Tết',
    '✨ Hiệu Ứng Glitch Art Xuân',
    '✨ Mưa Sao Băng',
    '✨ Bong Bóng Xà Phòng Ngũ Sắc',
    '✨ Cánh Hoa Hồng Bay',
    '✨ Lá Phong Đỏ May Mắn Rơi',
    '✨ Bướm Xuân Bay Dập Dìu',
    '✨ Đom Đóm Đêm Giao Thừa',
    '✨ Khói Màu Nghệ Thuật (Color Smoke)',
    '✨ Tia Nắng God Rays Xuyên Kẽ Lá',
    '✨ Hiệu Ứng Bokeh Trái Tim Ấm Áp',
    '✨ Hiệu Ứng Lens Flare Điện Ảnh',
    '✨ Giấy Màu Confetti Chúc Mừng',
    '✨ Tiền Đô La Bay (Rich Kid Tet)',
    '✨ Kim Cương Rơi (Luxury)',
    '✨ Hiệu Ứng Nước Chảy Bên Suối',
    '✨ Sấm Sét Uy Quyền (Thor)',
    '✨ Mây Ngũ Sắc (Tường Vân)',
    '✨ Hiệu Ứng Phim Cũ (Vintage Tet)',
    '✨ Hiệu Ứng Tranh Vẽ Chì',
    '✨ Hiệu Ứng Sơn Dầu Chảy',
    '✨ Hiệu Ứng Thủy Tinh Vỡ',
    '✨ Lửa Xanh Ma Thuật',
    '✨ Hào Quang Phật Pháp',
    '✨ Chữ Hỷ Bay (Tết & Cưới)',
    '✨ Chim Hạc Bay Về Trời',
    '✨ Rồng Bay Lượn (Dragon)',
    '✨ Phượng Hoàng Lửa (Phoenix)',
    '✨ Cá Chép Hóa Rồng (Success)',
    '✨ Hiệu Ứng 3D Pop-up',
    '✨ Hiệu Ứng Hologram Tương Lai',
    '✨ Hiệu Ứng Kính Vạn Hoa',
    '✨ Hiệu Ứng Slow Motion',
    '✨ Hiệu Ứng Double Exposure',
    '✨ Hiệu Ứng Gương Phản Chiếu',
    '✨ Hiệu Ứng Bóng Đổ Dài',
    '✨ Hiệu Ứng Silhouette (Ngược Sáng)',
    '✨ Hiệu Ứng Vignette (Tối Góc)'
];

export const STYLES = [
    // --- 50+ VIP STYLES ---
    '💎 8K Ultra-Realistic Luxury (Siêu Thực VIP)',
    '🎨 Tranh Sơn Dầu Cổ Điển (Oil Painting)',
    '🖌️ Tranh Thủy Mặc Á Đông (Ink Wash)',
    '📸 Nhiếp Ảnh Phim Nhựa 35mm (Vintage Film)',
    '🎮 3D CGI Pixar Style (Hoạt Hình 3D)',
    '🎎 Chibi Dễ Thương (Cute Chibi)',
    '🎥 Cinematic Movie Poster (Poster Điện Ảnh)',
    '🏙️ Cyberpunk Neon Future (Tết Tương Lai)',
    '📜 Tranh Dân Gian Đông Hồ (Folk Art)',
    '✨ Anime Ghibli Style (Thơ Mộng)',
    '🎨 Tranh Màu Nước (Watercolor)',
    '🎨 Tranh Khắc Gỗ (Woodblock Print)',
    '🎨 Tranh Sơn Mài Việt Nam (Lacquer)',
    '🎨 Tranh Lụa (Silk Painting)',
    '🎨 Phong Cách Retro 1990s (Tết Xưa)',
    '🎨 Phong Cách Vintage 1970s (Sài Gòn Xưa)',
    '🎨 Phong Cách Pop Art (Rực Rỡ)',
    '🎨 Phong Cách Impressionism (Ấn Tượng)',
    '🎨 Phong Cách Surrealism (Siêu Thực)',
    '🎨 Phong Cách Minimalism (Tối Giản)',
    '🎨 Phong Cách Gothic Huyền Bí',
    '🎨 Phong Cách Steampunk (Hơi Nước)',
    '🎨 Phong Cách Art Deco (Sang Trọng)',
    '🎨 Phong Cách Baroque (Cầu Kỳ)',
    '🎨 Phong Cách Renaissance (Phục Hưng)',
    '📸 Phong Cách Vogue Magazine (Tạp Chí)',
    '📸 Phong Cách National Geographic',
    '📸 Phong Cách Kodak Portra (Film)',
    '📸 Phong Cách Fujifilm (Màu Nhật)',
    '📸 Phong Cách Leica Monochrome (Đen Trắng)',
    '📸 Phong Cách Polaroid Instant (Lấy Liền)',
    '📸 Phong Cách High Key (Sáng Chói)',
    '📸 Phong Cách Low Key (Tối Bí Ẩn)',
    '📸 Phong Cách Macro (Siêu Cận Cảnh)',
    '📸 Phong Cách Drone (Flycam Trên Cao)',
    '🎮 Phong Cách Game Final Fantasy',
    '🎮 Phong Cách Game Genshin Impact',
    '🎮 Phong Cách Game League of Legends',
    '✨ Phong Cách Anime Makoto Shinkai',
    '✨ Phong Cách Manga Đen Trắng',
    '✨ Phong Cách Webtoon Hàn Quốc',
    '✨ Phong Cách Disney 2D Classic',
    '✨ Phong Cách Stop Motion (Đất Sét)',
    '✨ Phong Cách Paper Cut (Cắt Giấy)',
    '✨ Phong Cách Origami (Gấp Giấy)',
    '✨ Phong Cách Mosaic (Khảm)',
    '✨ Phong Cách Stained Glass (Kính Màu)',
    '✨ Phong Cách Pixel Art (8-bit)',
    '✨ Phong Cách Graffiti (Đường Phố)',
    '✨ Phong Cách Hàng Trống (Tranh Thờ)',
    '✨ Phong Cách Kim Hoàn (Jewelry Art)',
    '✨ Phong Cách Neon Noir (Đêm Huyền Bí)'
];

export const LAYOUTS = [
    '🎯 Chân dung trung tâm (1 ảnh toàn khung)',
    '🖼️ Toàn thân góc rộng (Lấy trọn bối cảnh)',
    '📸 Cận cảnh (Close-up focus mắt)',
    '👨‍👩‍👧‍👦 Gia đình sum vầy (Bố cục ngang)',
    '🎨 Bố cục tạp chí thời trang (Magazine)',
    '🎞️ 3 ẢNH DỌC: Breath of Light (Trên: Cận mắt ấm - Giữa: Tay chạm sáng - Dưới: Toàn thân bước đi)',
    '🎞️ 3 ẢNH DỌC: White Solitude (Trên: Mắt trầm - Giữa: Tay túi áo - Dưới: Dáng nhỏ bé)',
    '🎞️ 3 ẢNH DỌC: A Cup of Winter (Trên: Cận mặt hơi nước - Giữa: Tay giữ ly - Dưới: Bên cửa sổ)',
    '🎞️ 3 ẢNH DỌC: The Letter Unsent (Trên: Mắt tiếc nuối - Giữa: Cầm thư - Dưới: Bóng lưng)',
    '🎞️ 3 ẢNH DỌC: In the Snowy Silence (Trên: Mắt buồn - Giữa: Ngồi ghế - Dưới: Toàn cảnh ghế)',
    '🎞️ 3 ẢNH NGANG: Winter Glow (Trái: Cận mặt - Giữa: Nửa người - Phải: Toàn thân)',
    '🎞️ 3 ẢNH NGANG: Ember in White (3 mức độ ấm tăng dần, mặt nét)',
    '🎞️ 3 ẢNH NGANG: Snow & Heartbeat (1: Lo lắng - 2: Cười nhẹ - 3: Ôm áo)',
    '🎞️ 3 ẢNH NGANG: Goodbye Winter (1: Mắt - 2: Nửa người - 3: Bóng lưng)',
    '🎞️ 3 ẢNH NGANG: Midnight Snow (1: Mặt dưới đèn - 2: Dáng đi - 3: Phố đêm)',
    '⚡ 3 ẢNH ZIGZAG: Winter Story (Trên trái: Cận - Giữa phải: Nửa người - Dưới trái: Toàn thân)',
    '⚡ 3 ẢNH ZIGZAG: Snow Motion Flow (Mắt -> Tay -> Dáng đi theo đường chéo)',
    '⚡ 3 ẢNH ZIGZAG: Whispering Cold (Trên trái: Môi - Giữa phải: Nghiêng đầu - Dưới trái: Quay hông)',
    '⚡ 3 ẢNH ZIGZAG: Winter’s Voice (2 góc mặt chéo - Giữa: Nửa người)',
    '⚡ 3 ẢNH ZIGZAG: Snowlight Confession (Mắt -> Hoa -> Dáng đứng)',
    '💠 4 ẢNH DỌC: Winter Timeline (Sáng lạnh -> Ấm dần, mặt nét)',
    '💠 4 ẢNH CẢM XÚC: Emotion Stages (Bình tĩnh -> Suy tư -> Cười -> Nhắm mắt)',
    '💠 4 ẢNH THANG MƠ: Dream Ladder (Toàn thân -> Nửa người -> Cận -> Siêu cận)',
    '💠 4 ẢNH NGANG: Film Strip (Góc xa -> Gần -> Nửa người -> Mặt)',
    '💠 4 ẢNH TONE: Mood Symphony (Chuyển xanh lạnh sang vàng ấm)',
    '💠 4 ẢNH KIM CƯƠNG: Diamond Frame (Trên: Mắt - Trái/Phải: Nửa người - Dưới: Toàn thân)',
    '💠 3 KHUNG TAM GIÁC: Triangle Flow (Đỉnh: Mặt cận - 2 góc dưới: Body)',
    '💠 4 ẢNH MOSAIC: Mirror Mosaic (4 góc mặt khác nhau siêu nét)',
    '💠 4 ẢNH LĂNG KÍNH: Prism Light (1 mặt chính + 3 chi tiết nhỏ)',
    '💠 4 ẢNH BẤT ĐỐI XỨNG: Royal Montage (1 mặt lớn + các khung nhỏ chi tiết)',
    '📐 Tỷ lệ vàng (Golden Ratio)',
    '📐 Quy tắc một phần ba (Rule of Thirds)',
    '📐 Đường dẫn hướng (Leading Lines)',
    '📐 Khung trong khung (Frame within Frame)',
    '📐 Đối xứng hoàn hảo (Symmetry)',
    '📐 Góc nghiêng nghệ thuật (Dutch Angle)',
    '📐 Chụp từ trên xuống (Top Down/Flat Lay)',
    '📐 Chụp từ dưới lên (Low Angle Heroic)',
    '📐 Góc nhìn qua vai (Over the Shoulder)',
    '📐 Bố cục đường chéo (Diagonal)',
    '📐 Bố cục hình tam giác (Triangle)',
    '📐 Bố cục hình tròn (Circular)',
    '📐 Bố cục không gian âm (Negative Space)',
    '📐 Bố cục lấp đầy khung hình (Fill the Frame)',
    '📐 Bố cục phản chiếu (Reflection)',
    '📐 Chụp xuyên khe (Through the Gap)',
    '📐 Chụp bóng đổ (Shadow Play)',
    '📐 Chụp ngược sáng (Silhouette)',
    '📐 Chụp chuyển động (Motion Blur)',
    '📐 Chụp lia máy (Panning)',
    '📐 Chụp phơi sáng lâu (Long Exposure)',
    '📐 Chụp macro mắt (Eye Macro)',
    '📐 Chụp bàn tay (Hand Focus)',
    '📐 Chụp đôi giày (Shoes Focus)',
    '📐 Chụp phụ kiện (Accessories Focus)',
    '📐 Selfie góc rộng',
    '📐 Selfie trước gương',
    '📐 Ảnh thẻ nghệ thuật',
    '📐 Ảnh bìa Facebook',
    '📐 Story Instagram (Dọc)',
    '📐 Thumbnail Youtube (Ngang)',
    '📐 Poster Phim (Dọc)',
    '📐 Banner Quảng Cáo (Ngang)',
    '📐 Bố cục Panorama (Toàn Cảnh)',
    '📐 Bố cục Fisheye (Mắt Cá)',
    '📐 Bố cục Triptych (3 Tấm)',
    '📐 Bố cục Collage (Ghép Ảnh)',
    '📐 Bố cục Split Screen (Chia Màn Hình)',
    '📐 Bố cục Double Exposure (Chồng Ảnh)',
    '📐 Bố cục Minimalist (Tối Giản)',
    '📐 Bố cục Maximalist (Nhiều Chi Tiết)',
    '📐 Bố cục Abstract (Trừu Tượng)',
    '📐 Bố cục Surreal (Siêu Thực)'
];

export const BORDERS = [
    // --- 50+ VIP TET BORDERS ---
    '🛑 Không viền',
    '🌸 Viền Hoa Đào Phai (Peach Blossom)',
    '🌼 Viền Hoa Mai Vàng (Yellow Apricot)',
    '🧧 Viền Câu Đối Đỏ Thư Pháp',
    '🎋 Viền Tre Trúc Xanh (Bamboo)',
    '⚜️ Viền Vàng Hoàng Gia (Royal Gold)',
    '🏮 Viền Đèn Lồng Đỏ (Lanterns)',
    '🎆 Viền Pháo Hoa Rực Rỡ (Fireworks)',
    '🖼️ Viền Gỗ Cổ Điển Chạm Khắc',
    '🖼️ Viền Tranh Sơn Dầu Sang Trọng',
    '🖼️ Viền Mạ Vàng 24K Đính Đá',
    '🖼️ Viền Bạc Platinum (Silver)',
    '🖼️ Viền Kim Cương Lấp Lánh',
    '🖼️ Viền Ngọc Trai Quý Phái',
    '🖼️ Viền Đá Ruby Đỏ May Mắn',
    '🖼️ Viền Neon Cyberpunk Tết',
    '🖼️ Viền Hoa Hồng Nhung Đỏ',
    '🖼️ Viền Hoa Sen Hồng Tinh Khiết',
    '🖼️ Viền Lá Chuối Xanh Mướt',
    '🖼️ Viền Mây Ngũ Sắc (Tường Vân)',
    '🖼️ Viền Rồng Phượng Sum Vầy',
    '🖼️ Viền Trống Đồng Đông Sơn',
    '🖼️ Viền Gốm Sứ Bát Tràng',
    '🖼️ Viền Lụa Đỏ Mềm Mại',
    '🖼️ Viền Giấy Dó Truyền Thống',
    '🖼️ Viền Film Cũ Hoài Niệm',
    '🖼️ Viền Polaroid Trắng Hiện Đại',
    '🖼️ Viền Instagram Story Tết',
    '🖼️ Viền Facebook Post Tết',
    '🖼️ Viền Thiệp Chúc Tết Sang Trọng',
    '🖼️ Viền Bao Lì Xì Đỏ Thắm',
    '🖼️ Viền Đồng Xu Vàng Tài Lộc',
    '🖼️ Viền Cành Lộc Biếc Đầu Xuân',
    '🖼️ Viền Chim Én Mùa Xuân',
    '🖼️ Viền Bánh Chưng Bánh Tét',
    '🖼️ Viền Dưa Hấu Đỏ May Mắn',
    '🖼️ Viền Mâm Ngũ Quả Sung Túc',
    '🖼️ Viền Chữ Thư Pháp "Phúc"',
    '🖼️ Viền Họa Tiết Cung Đình Huế',
    '🖼️ Viền Gốm Men Lam Cổ',
    '🖼️ Viền Họa Tiết Thổ Cẩm Tây Bắc',
    '🖼️ Viền Minimalist Line Gold',
    '🖼️ Viền Geometric Art Deco',
    '🖼️ Viền Brush Stroke Mực Tàu',
    '🖼️ Viền Watercolor Splash Xuân',
    '🖼️ Viền Bụi Vàng (Gold Dust)',
    '🖼️ Viền Đêm Sao Giao Thừa',
    '🖼️ Viền Galaxy Vũ Trụ Tết',
    '🖼️ Viền Tuyết Rơi Mùa Xuân',
    '🖼️ Viền Happy New Year 2026',
    '🖼️ Viền Cung Chúc Tân Xuân',
    '🖼️ Viền Vạn Sự Như Ý',
    '🖼️ Viền Lân Sư Rồng',
    '🖼️ Viền Con Ngựa Vàng (Năm Ngọ)'
];

export const ACCESSORIES = [
    // --- 50+ VIP TET ACCESSORIES ---
    '🚗 Siêu Xe Mercedes G63 Chở Đào Tết',
    '🚗 Siêu Xe Porsche 911 Màu Đỏ Lì Xì',
    '🚗 Siêu Xe Audi R8 V10 Spyder Du Xuân',
    '🚗 Siêu Xe McLaren 720S Vàng Mai',
    '🚗 Siêu Xe Ford Mustang Shelby GT500',
    '🚗 Siêu Xe Chevrolet Corvette C8',
    '🚗 Siêu Xe Maserati MC20',
    '🚗 Siêu Xe Lexus LFA (Huyền Thoại)',
    '🚗 Siêu Xe Nissan GT-R Nismo',
    '🚗 Siêu Xe Tesla Roadster (SpaceX)',
    '🚗 Siêu Xe VinFast VF9 President Độ Limousine',
    '🏍️ Moto Harley-Davidson CVO Chở Mai',
    '🏍️ Moto Triumph Rocket 3',
    '🏍️ Moto Yamaha R1M',
    '🏍️ Moto Honda Gold Wing (Phi Thuyền)',
    '🛥️ Du Thuyền Riva Aquarama Trên Sông Hương',
    '🛥️ Du Thuyền Sunseeker Predator Hạ Long',
    '✈️ Trực Thăng Airbus H160 (VIP) Ngắm Pháo Hoa',
    '✈️ Trực Thăng Bell 525 Relentless',
    '✈️ Thủy Phi Cơ Cessna Caravan',
    '⌚ Đồng Hồ Audemars Piguet Royal Oak Gold',
    '⌚ Đồng Hồ Vacheron Constantin Overseas',
    '⌚ Đồng Hồ Cartier Santos Đính Kim Cương',
    '⌚ Đồng Hồ Omega Speedmaster (Moonwatch)',
    '⌚ Đồng Hồ Tag Heuer Monaco',
    '🏠 Biệt Thự Vinhome Riverside Trang Trí Tết',
    '🏠 Biệt Thự Ecopark Ngập Tràn Hoa',
    '🏠 Penthouse Metropole Thủ Thiêm View Pháo Hoa',
    '🏠 Dinh Thự The Rivus Elie Saab Dát Vàng',
    '🏨 Khách Sạn Burj Al Arab Dubai',
    '💍 Vòng Cổ Ngọc Trai (Pearl Necklace)',
    '👒 Nón Lá Truyền Thống (Conical Hat)',
    '🧣 Khăn Rằn Nam Bộ (Scarf)',
    '🕶️ Kính Râm Thời Trang Gucci',
    '📿 Chuỗi Hạt Trầm Hương (Agarwood)',
    '👑 Mấn Đội Đầu Đính Ngọc (Headpiece)',
    '💎 Trang Sức Kim Cương (Diamond Jewelry)',
    '👜 Túi Xách Hermes Birkin Da Cá Sấu',
    '⌚ Đồng Hồ Rolex Day-Date Vàng Khối',
    '🪭 Quạt Giấy Thư Pháp (Paper Fan)',
    '🪭 Quạt Lụa Cầm Tay (Silk Fan)',
    '🪭 Quạt Lông Vũ Sang Trọng',
    '🎀 Nơ Cài Tóc Nhung Đỏ',
    '🥢 Trâm Cài Tóc Phượng Hoàng',
    '🌸 Hoa Cài Tóc Đào Phai',
    '🧢 Mũ Lưỡi Trai Hàng Hiệu',
    '🎩 Mũ Phớt (Fedora) Quý Ông',
    '🎩 Mũ Beret (Nồi) Dạ',
    '🧣 Khăn Choàng Lụa Hermès',
    '🧣 Khăn Len Burberry',
    '🧤 Găng Tay Dạ Hội Satin',
    '🧤 Găng Tay Da Lái Xe',
    '👢 Giày Cao Gót Louboutin Đế Đỏ',
    '👢 Boots Da Cổ Cao',
    '👟 Giày Sneaker Balenciaga',
    '👡 Guốc Mộc Vẽ Hoa Sen',
    '👓 Kính Cận Gọng Vàng 18K',
    '👓 Kính Mắt Mèo Sang Chảnh',
    '👂 Bông Tai Vàng 24K',
    '👂 Bông Tai Ngọc Bích Phong Thủy',
    '💍 Nhẫn Kim Cương Hột Xoàn',
    '💍 Nhẫn Cẩm Thạch Bọc Vàng',
    '📿 Vòng Tay Pandora Charm Tết',
    '👜 Ví Cầm Tay (Clutch) Đính Đá',
    '🎒 Ba Lô Louis Vuitton',
    '🌂 Ô Giấy Dầu Cổ Trang',
    '🌂 Ô Trong Suốt Đi Mưa Xuân',
    '📱 Ốp Lưng Điện Thoại Thần Tài',
    '🎧 Tai Nghe Airpods Max Gold',
    '📸 Máy Ảnh Leica Cổ Điển',
    '🎸 Đàn Guitar Acoustic',
    '🎻 Đàn Violin Cổ Điển',
    '🎹 Đàn Tranh Việt Nam',
    '🧸 Gấu Bông Mặc Áo Dài',
    '🎈 Chùm Bóng Bay Chúc Mừng Năm Mới',
    '🏮 Đèn Lồng Con Thỏ',
    '🏮 Đèn Lồng Kéo Quân'
];

export const HANDHELD_ITEMS = [
    // --- 20 NEW ULTRA LUXURY & GIANT BEAR PROPS ---
    '🐻 Ôm Gấu Brown Khổng Lồ 2m (Line Friends)',
    '🧸 Ôm Gấu Teddy Bear Size Đại (Lông Cừu Mềm)',
    '🐰 Ôm Thỏ Jellycat Khổng Lồ (Bunny) Dễ Thương',
    '🍓 Ôm Gấu Bông Lotso Dâu Tây (Disney Pixar)',
    '👑 Cầm Vương Miện Miss Universe (Power of Unity)',
    '💎 Cầm Quyền Trượng Kim Cương (Royal Scepter)',
    '💐 Ôm Bó Hoa Tiền Đô La (100 Tờ 100$)',
    '📱 Cầm Siêu Sim Số Đẹp (Bát Quý 8) Dát Vàng',
    '🔑 Cầm Chìa Khóa Siêu Xe Bugatti Centodieci',
    '🥚 Cầm Trứng Vàng Fabergé (Trị Giá Triệu Đô)',
    '🏺 Cầm Bình Gốm Minh Mạng Cổ (Vô Giá)',
    '🏠 Cầm Sổ Đỏ Biệt Thự (Bìa Mạ Vàng)',
    '💼 Cầm Vali Tiền Vàng (Money Heist Style)',
    '🏆 Cầm Tượng Vàng Oscar (Thật 100%)',
    '💍 Cầm Viên Kim Cương Hồng (Pink Star Diamond)',
    '🐈 Ôm Mèo Thần Tài Vàng Khối 9999',
    '🪶 Cầm Quạt Lông Vũ Đà Điểu (Hoàng Gia Anh)',
    '🎸 Cầm Đàn Tỳ Bà Ngọc Bích (Cổ Trang VIP)',
    '🚬 Cầm Hộp Xì Gà Cohiba Behike (Limited)',
    '🍾 Cầm Chai Rượu Macallan 1926 (60 Năm)',

    // --- 50+ VIP TET PROPS (EXISTING) ---
    '💎 Quyền Trượng Rồng Vàng (Dragon Scepter)',
    '🧧 Bao Lì Xì Khổng Lồ Dát Vàng',
    '🌸 Cành Đào Tiên 3000 Năm (Cực Phẩm)',
    '👑 Vương Miện Miss Universe Power of Unity',
    '💰 Vali Tiền Đô La (Money Heist)',
    '🍾 Chai Rượu Vang Romanée-Conti 1945',
    '⚜️ Quạt Lông Công Hoàng Gia (Peacock Fan)',
    '🏮 Đèn Lồng Kéo Quân Dát Vàng',
    '📜 Chiếu Chỉ Vua Ban (Royal Decree)',
    '🎻 Đàn Tỳ Bà Ngọc Bích',
    '🔮 Quả Cầu Pha Lê Tiên Tri',
    '🏺 Bình Gốm Chu Đậu Cổ Vẽ Vàng',
    '🦅 Chim Ưng Săn Mồi (Trên Tay)',
    '🐎 Dây Cương Ngựa Chiến (Golden Reins)',
    '🗝️ Chìa Khóa Vàng Mở Cổng Trời',
    '🎋 Cây Nêu Ngày Tết (Mini)',
    '🥓 Đùi Heo Muối Iberico (Nguyên Cái)',
    '🍫 Hộp Chocolate Godiva Vàng',
    '📱 iPhone 16 Pro Max Mạ Vàng 24K',
    '👜 Túi Hermes Birkin Himalaya (Cầm Tay)',
    '🧧 Xấp Bao Lì Xì Đỏ Dày Cộm',
    '🌸 Cành Đào Phai Nhật Tân',
    '🌼 Cành Mai Vàng Yên Tử',
    '🏮 Lồng Đèn Đỏ Hội An',
    '📜 Câu Đối Tết Thư Pháp',
    '🎁 Hộp Quà Tết Cao Cấp (Yến Sào/Rượu)',
    '🍉 Miếng Dưa Hấu Khắc Chữ Phúc',
    '🥮 Bánh Chưng Vuông Vức',
    '🥮 Đòn Bánh Tét Miền Tây',
    '🍵 Tách Trà Sen Nóng Hổi',
    '🍷 Ly Rượu Vang Đỏ Sóng Sánh',
    '🥂 Ly Champagne Nâng Chúc Mừng',
    '🍺 Ly Bia Mát Lạnh Zô 100%',
    '☕ Ly Cà Phê Trứng Giảng',
    '🧋 Ly Trà Sữa Full Topping',
    '🍦 Cây Kem Tràng Tiền',
    '🍡 Xiên Kẹo Hồ Lô Đỏ',
    '🍭 Kẹo Mút Khổng Lồ 7 Màu',
    '🍎 Quả Táo Đỏ Phú Quý',
    '🍊 Quả Cam Vàng Tài Lộc',
    '🍍 Quả Dứa (Thơm) Phụng Nghi',
    '🥥 Trái Dừa Lửa May Mắn',
    '💐 Bó Hoa Hồng 999 Bông',
    '💐 Bó Hoa Hướng Dương Mặt Trời',
    '💐 Bó Hoa Baby Trắng Tinh Khôi',
    '🖋️ Bút Lông Đại Tự',
    '📖 Quyển Sách "Đắc Nhân Tâm"',
    '🎤 Micro Vàng Hát Karaoke',
    '🎮 Tay Cầm Game PS5',
    '💳 Thẻ Tín Dụng Đen (Black Card)',
    '🔑 Chìa Khóa Xe Ferrari',
    '💄 Thỏi Son Louboutin',
    '🪞 Gương Cầm Tay Hoàng Cung',
    '🚬 Tẩu Thuốc Gỗ Hương (Vintage)',
    '🕯️ Cây Nến Thơm Chill',
    '🧨 Dây Pháo Đỏ Giả',
    '🎇 Pháo Bông Que Lấp Lánh',
    '🐉 Đầu Lân Mini Dễ Thương',
    '👺 Mặt Nạ Ông Địa Cười',
    '🏏 Vợt Cầu Lông Yonex',
    '🎾 Vợt Tennis Wilson',
    '⚽ Quả Bóng Đá World Cup',
    '🏀 Quả Bóng Rổ Spalding',
    '🛹 Ván Trượt Supreme',
    '🏄 Ván Lướt Sóng Chanel',
    '🎣 Cần Câu Cá Shimano',
    '🗡️ Kiếm Cổ Trang (Sword)',
    '🏹 Cung Tên Tình Yêu (Cupid)'
];

export const PETS = [
    // --- 50+ VIP TET PETS ---
    '🐎 Ngựa Bạch Mã Hoàng Gia (Năm Ngọ)',
    '🐎 Ngựa Xích Thố Chiến Mã',
    '🐎 Ngựa Pony Dễ Thương',
    '🐎 Ngựa Vàng Tài Lộc',
    '🐈 Mèo Thần Tài Vẫy Tay (Maneki Neko)',
    '🐕 Cún Con Đội Mũ Lân',
    '🐉 Rồng Con Chibi Phun Lửa',
    '🕊️ Chim Bồ Câu Trắng Hòa Bình',
    '🐠 Cá Chép Vàng Vượt Vũ Môn',
    '🐈 Mèo Mướp Mặc Áo Dài',
    '🐈 Mèo Anh Lông Ngắn Quý Tộc',
    '🐈 Mèo Ba Tư Sang Chảnh',
    '🐕 Chó Corgi Mông To Đeo Nơ',
    '🐕 Chó Husky Ngáo Đón Tết',
    '🐕 Chó Golden Retriever Hiền Lành',
    '🐕 Chó Shiba Inu Cười',
    '🐕 Chó Poodle Tỉa Lông Đẹp',
    '🐇 Thỏ Ngọc Cung Trăng',
    '🐹 Chuột Hamster Cầm Lì Xì',
    '🦜 Vẹt Đuôi Dài Nam Mỹ',
    '🦚 Chim Công Xòe Đuôi Rực Rỡ',
    '🦅 Đại Bàng Tung Cánh',
    '🦉 Cú Mèo Thông Thái',
    '🦢 Thiên Nga Trắng Hồ Gươm',
    '🦆 Vịt Con Uyên Ương',
    '🐔 Gà Trống Vàng Gáy Sáng',
    '🐥 Đàn Gà Con Lông Vàng',
    '🐷 Heo Đất Tiết Kiệm (Piggy Bank)',
    '🐷 Heo Con Mũm Mĩm',
    '🐮 Bò Sữa Đeo Chuông Vàng',
    '🐃 Trâu Vàng Đinh Sửu',
    '🐅 Hổ Con (Tiger Cub) Dễ Thương',
    '🦁 Sư Tử Con (Lion Cub) Simba',
    '🐼 Gấu Trúc Ăn Trúc',
    '🐨 Gấu Koala Úc',
    '🐻 Gấu Brown (Line Friends)',
    '🦄 Kỳ Lân Cầu Vồng (Unicorn)',
    '🦖 Khủng Long T-Rex Mini',
    '🐢 Rùa Vàng Hồ Gươm',
    '🦋 Bướm Khổng Lồ Tiên Cảnh',
    '🐝 Ong Vàng Chăm Chỉ Hút Mật',
    '🐞 Bọ Cánh Cam May Mắn',
    '🦀 Cua Hoàng Đế Alaska',
    '🦞 Tôm Hùm Canada',
    '🐙 Bạch Tuộc Cute Cảm Xúc',
    '🐬 Cá Heo Nhảy Múa',
    '🐳 Cá Voi Xanh Đại Dương',
    '🦈 Cá Mập Baby Shark',
    '🐍 Rắn Con Quấn Quýt',
    '🐒 Khỉ Con Tinh Nghịch',
    '🐐 Dê Con Hiền Lành',
    '🦊 Cáo Tuyết Chín Đuôi (Cửu Vĩ Hồ)',
    '🦌 Tuần Lộc Mũi Đỏ',
    '🦩 Hồng Hạc Kiêu Sa'
];

export const TET_BACKGROUNDS = [
    // --- 50+ VIP TET BACKGROUNDS ---
    '🏰 Cung Điện Vàng Versailles Đón Tết',
    '🕌 Đền Taj Mahal Lúc Bình Minh Xuân',
    '🏙️ Penthouse View Toàn Cảnh New York Đêm Giao Thừa',
    '🌌 Trạm Vũ Trụ ISS View Trái Đất Đón Tết',
    '🛥️ Bến Du Thuyền Monaco Sang Chảnh Mùa Xuân',
    '🏔️ Đỉnh Everest Tuyết Phủ Cắm Cờ Tổ Quốc',
    '🌋 Miệng Núi Lửa Hawaii (An Toàn) Picnic Tết',
    '🏝️ Đảo Thiên Đường Maldives (Resort 6 Sao) Tết',
    '🎰 Sòng Bài Casino Monte Carlo Lộng Lẫy',
    '🕍 Thánh Đường St. Peter (Vatican) Cầu Nguyện',
    '🌉 Cầu Vàng Đà Nẵng Trong Mây Xuân',
    '🏯 Lâu Đài Himeji Mùa Hoa Anh Đào Nở Rộ',
    '🏜️ Kim Tự Tháp Giza Ai Cập Huyền Bí',
    '🌊 Rạn San Hô Great Barrier Reef Đón Tết Dưới Nước',
    '🎍 Vườn Thượng Uyển Nhật Bản (Zen Garden) Tĩnh Lặng',
    '🦁 Đồng Cỏ Savanna Châu Phi (Safari) Mùa Xuân',
    '❄️ Làng Tuyết Hallstatt Cổ Tích Đêm 30',
    '🏮 Tử Cấm Thành Bắc Kinh Đêm Nguyên Tiêu',
    '🌃 Skyline Dubai (Burj Khalifa) Pháo Hoa',
    '🏞️ Hẻm Tu Sản - Sông Nho Quế Hùng Vĩ Mùa Xuân',
    '🕌 Chùa Một Cột Cổ Kính Uy Nghiêm',
    '🏘️ Phố Cổ Hội An Đèn Lồng Rực Rỡ',
    '🏙️ Đường Hoa Nguyễn Huệ Sài Gòn Đông Đúc',
    '🏡 Nhà Rường Huế Cổ Kính Rêu Phong',
    '🌲 Vườn Đào Nhật Tân Nở Rộ Hồng Thắm',
    '🌼 Vườn Mai Vàng Bến Tre Rực Rỡ',
    '🎇 Bầu Trời Pháo Hoa Đêm Giao Thừa Hồ Gươm',
    '🏠 Phòng Khách Biệt Thự Sang Trọng Đón Khách',
    '🏮 Phố Hàng Mã Hà Nội Rực Đỏ',
    '🌾 Cánh Đồng Lúa Chín Vàng Mùa Gặt Tết',
    '🏖️ Bãi Biển Phú Quốc Nắng Vàng Cát Trắng',
    '🏔️ Đỉnh Fansipan Săn Mây Ngày Tết',
    '🏞️ Thác Bản Giốc Hùng Vĩ Nước Đổ',
    '🌲 Rừng Thông Đà Lạt Mơ Màng Sương Sớm',
    '🏜️ Đồi Cát Mũi Né Vàng Óng',
    '🏙️ Sân Thượng Bitexco Chill Pháo Hoa',
    '🌉 Cầu Rồng Đà Nẵng Phun Lửa',
    '🏯 Hoàng Thành Huế Uy Nghi Trầm Mặc',
    '🕍 Nhà Thờ Đức Bà Sài Gòn Nắng Sớm',
    '🎭 Nhà Hát Lớn Hà Nội Kiến Trúc Pháp',
    '🏫 Chợ Bến Thành Nhộn Nhịp Sắm Tết',
    '🏪 Cửa Hàng Tiện Lợi Circle K Đêm 30',
    '☕ Quán Cà Phê Vintage Góc Phố Cổ',
    '📚 Thư Viện Cổ Điển Harry Potter',
    '🎨 Bảo Tàng Mỹ Thuật Đông Dương',
    '🏟️ Sân Vận Động Mỹ Đình Cuồng Nhiệt',
    '🎡 Công Viên Sun World Ba Na Hills',
    '🎪 Rạp Xiếc Trung Ương Vui Nhộn',
    '🚀 Trạm Vũ Trụ NASA (Sci-fi Tet)',
    '🌑 Bề Mặt Mặt Trăng Cắm Cành Đào',
    '🏰 Lâu Đài Disney Cổ Tích Pháo Hoa',
    '🏠 Nhà Sàn Tây Bắc Bếp Lửa Hồng',
    '🚤 Chợ Nổi Cái Răng Miền Tây Sông Nước',
    '🎋 Lũy Tre Làng Yên Bình Chiều 30',
    '⛩️ Cổng Torii Nhật Bản Đỏ Thắm',
    '🏯 Vạn Lý Trường Thành Tuyết Phủ',
    '🗼 Tháp Eiffel Paris Lấp Lánh Đèn',
    '🗽 Tượng Nữ Thần Tự Do NYC Đội Nón Lá',
    '🌉 Cầu Tháp London (Tower Bridge)',
    '🕋 Kim Tự Tháp Ai Cập Cưỡi Lạc Đà',
    '🏟️ Đấu Trường La Mã Colosseum',
    '🏔️ Núi Phú Sĩ Nhật Bản Hoa Anh Đào',
    '🌃 Đường Phố Tokyo Neon Cyberpunk',
    '🌃 Đường Phố Hong Kong Neon Bảng Hiệu',
    '🌃 Đường Phố Seoul Mùa Đông Tuyết Rơi',
    '🏞️ Hồ Gươm Hà Nội Tháp Rùa Cổ Kính',
    '🏞️ Vịnh Hạ Long Kỳ Quan Thiên Nhiên',
    '🏞️ Tràng An Ninh Bình Non Nước Hữu Tình',
    '🏞️ Hang Sơn Đoòng Kỳ Bí'
];

export const TET_OUTFITS_FEMALE = [
    // --- 50+ VIP FEMALE OUTFITS (TET) ---
    '👗 Áo Bà Ba Màu Mỡ Gà (Chân Quê Tết)',
    '👗 Áo Tứ Thân Mớ Ba Mớ Bảy (Hội Lim Xuân)',
    '👗 Áo Dài Lemur (Tân Thời 1930) Quý Phái',
    '👗 Áo Dài Cô Ba Sài Gòn Chấm Bi Retro',
    '👗 Váy Yếm Denim Cách Tân Năng Động',
    '👗 Set Blazer Croptop Gen Z Đi Chúc Tết',
    '👗 Váy Loli Gothic Đỏ Đen (Cosplay Tết)',
    '👗 Trang Phục Wonder Woman Giáp Vàng',
    '👗 Áo Choàng Nữ Hoàng Băng Giá Elsa (Tết Lạnh)',
    '👗 Váy Dạ Hội Đính Lông Vũ Thiên Nga',
    '👗 Áo Dài Gấm Thái Tuấn Sang Trọng',
    '👗 Áo Dài Lụa Tơ Tằm Bảo Lộc Cao Cấp',
    '👗 Váy Cưới Công Nương Diana (Đuôi Dài 8m)',
    '👗 Bộ Đồ Phi Hành Gia Nữ Sexy',
    '👗 Trang Phục Nữ Chiến Binh Wakanda',
    '👗 Váy Đầm Xòe Dior Tiểu Thư Đi Chùa',
    '👗 Áo Sơ Mi Lụa Gucci (Office Chic)',
    '👗 Áo Phông Balenciaga Oversize Đi Chơi',
    '👗 Set Đồ Chanel Tweed Hồng (Jennie Style)',
    '👗 Váy Cưới Marchesa Công Chúa Lộng Lẫy',
    '👗 Áo Dài Nhung Đen Đính Đá Quý Bà',
    '👗 Đầm Dạ Hội Xẻ Tà Cao Thảm Đỏ',
    '👗 Trang Phục Catwoman Da Bóng Quyến Rũ',
    '👗 Váy Lolita Nhật Bản Dễ Thương',
    '👗 Trang Phục Cổ Trang Trung Quốc (Hán Phục)',
    '👗 Trang Phục Bollywood Ấn Độ (Sari Vàng)',
    '👗 Áo Khoác Dài Burberry Anh Quốc',
    '👗 Váy Ngắn Miu Miu Trend Mới Nhất',
    '👗 Đồ Bơi Versace Họa Tiết Vàng (Resort)',
    '👗 Áo Dài Cách Tân Váy Xòe Trẻ Trung',
    '👗 Áo Dài Đỏ Truyền Thống Thêu Hoa',
    '👗 Áo Dài Vàng Hoàng Gia Quyền Quý',
    '👗 Áo Dài Hồng Pastel Ngọt Ngào',
    '👗 Áo Dài Trắng Tinh Khôi Nữ Sinh',
    '👗 Áo Dài Cách Tân Tay Phồng Hiện Đại',
    '👗 Áo Tứ Thân Bắc Bộ Nón Quai Thao',
    '👗 Áo Bà Ba Nam Bộ Khăn Rằn',
    '👗 Váy Dạ Hội Lộng Lẫy Đi Tiệc Tất Niên',
    '👗 Cổ Phục Nhật Bình Triều Nguyễn',
    '👗 Sườn Xám Thượng Hải Quyến Rũ',
    '👗 Áo Dài Nhung Đỏ Đô Sang Trọng',
    '👗 Áo Dài Gấm Thêu Rồng Phượng',
    '👗 Áo Dài Lụa Hà Đông Mềm Mại',
    '👗 Áo Dài Tay Loe Cách Điệu',
    '👗 Áo Dài Cổ Yếm Gợi Cảm',
    '👗 Áo Dài Ren Xuyên Thấu Tinh Tế',
    '👗 Áo Dài Đính Kết Cườm Thủ Công',
    '👗 Áo Dài Vẽ Tay Nghệ Thuật Sen Hạc',
    '👗 Áo Dài Ombre Chuyển Màu Độc Đáo',
    '👗 Váy Công Chúa (Princess Dress) Cổ Tích',
    '👗 Váy Cưới (Wedding Dress) Lộng Lẫy',
    '👗 Váy Vintage Hoa Nhí Nhẹ Nhàng',
    '👗 Váy Maxi Đi Biển Mùa Xuân',
    '👗 Váy Ngắn Trẻ Trung Năng Động',
    '👗 Set Blazer Công Sở Thanh Lịch',
    '👗 Set Tweed Sang Chảnh Tiểu Thư',
    '👗 Hanbok Hàn Quốc Truyền Thống',
    '👗 Kimono Nhật Bản Hoa Anh Đào',
    '👗 Sari Ấn Độ Lấp Lánh',
    '👗 Trang Phục Dân Tộc Hmong Sặc Sỡ',
    '👗 Trang Phục Dân Tộc Thái Duyên Dáng',
    '👗 Trang Phục Cosplay Anime Nhật Bản',
    '👗 Trang Phục Chiến Binh (Warrior) Mạnh Mẽ',
    '👗 Trang Phục Tiên Nữ (Fairy) Cánh Bướm',
    '👗 Trang Phục Phi Hành Gia Tương Lai',
    '👗 Trang Phục Nữ Sinh (Schoolgirl) Nhật',
    '👗 Trang Phục Y Tá Quyến Rũ',
    '👗 Trang Phục Cảnh Sát Ngầu',
    '👗 Bikini Đi Biển Mùa Tết',
    '👗 Đồ Tập Gym/Yoga Khoe Dáng',
    '👗 Pyjama Lụa Mặc Nhà Ấm Áp',
    '👗 Áo Thun Quần Jeans Năng Động',
    '👗 Áo Hoodie Streetwear Cool Ngầu',
    '👗 Áo Croptop Khoe Eo Con Kiến',
    '👗 Áo Len Mùa Đông Ấm Áp',
    '👗 Áo Khoác Lông Thú (Faux Fur) Sang Chảnh',
    '👗 Áo Khoác Da (Leather Jacket) Biker',
    '👗 Áo Khoác Denim Bụi Bặm'
];

export const TET_OUTFITS_MALE = [
    // --- 50+ VIP MALE OUTFITS (TET) ---
    '👔 Áo Sơ Mi Trắng Soái Ca (Ướt Át)',
    '👔 Áo Thun Đen Body Khoe Cơ Bắp',
    '👔 Áo Khoác Bomber Phi Công Top Gun',
    '👔 Áo Gile Len Phong Cách Ông Nội (Grandpacore)',
    '👔 Bộ Đồ Bà Ba Đen Công Tử Bạc Liêu',
    '👔 Trang Phục Vua Càn Long Du Giang Nam',
    '👔 Trang Phục Thần Thor Áo Choàng Đỏ',
    '👔 Trang Phục Captain America',
    '👔 Trang Phục Spider-Man Miles Morales',
    '👔 Áo Khoác Da Biker Sơn Tùng M-TP',
    '👔 Vest Kẻ Sọc Peaky Blinders',
    '👔 Trang Phục Godfather Hoa Hồng Đỏ',
    '👔 Áo Choàng Doctor Strange Phép Thuật',
    '👔 Bộ Suit Kingsman Dù & Kính',
    '👔 Trang Phục Samurai Ronin Nhật Bản',
    '👔 Áo Thun Polo Ralph Lauren Cổ Điển',
    '👔 Áo Len Cashmere Loro Piana Xa Xỉ',
    '👔 Áo Khoác Denim Levi\'s Bụi Bặm',
    '👔 Bộ Suit Armani Doanh Nhân Thành Đạt',
    '👔 Trang Phục Thể Thao Nike Năng Động',
    '👔 Áo Dài Ngũ Thân Tay Chẽn Cổ Phục',
    '👔 Trang Phục Quan Triều Nguyễn Mũ Cánh Chuồn',
    '👔 Áo Vest Nhung Xanh Joker',
    '👔 Trang Phục Batman Giáp Đen',
    '👔 Áo Choàng Harry Potter Gryffindor',
    '👔 Trang Phục Star Wars Jedi',
    '👔 Bộ Đồ Lặn Biển Scuba Diving',
    '👔 Trang Phục Leo Núi The North Face',
    '👔 Áo Thun In Hình Rồng Street Style',
    '👔 Bộ Pyjama Lụa Tơ Tằm Sang Trọng',
    '👔 Áo Dài Nam Truyền Thống Khăn Đóng',
    '👔 Áo Dài Nam Cách Tân Hiện Đại',
    '👔 Vest Lịch Lãm (Suit) Đi Chúc Tết',
    '👔 Sơ Mi Trắng Soái Ca Cổ Cồn',
    '👔 Áo Bà Ba Nam Bộ Chân Chất',
    '👔 Áo Gấm Rồng Phượng Đỏ Thắm',
    '👔 Áo Dài Ngũ Thân Truyền Thống',
    '👔 Áo Dài Nhung Đen Quý Phái',
    '👔 Áo Dài Họa Tiết Trống Đồng Hào Hùng',
    '👔 Áo Dài Vẽ Rồng Bay Phượng Múa',
    '👔 Tuxedo Đen Sang Trọng Dự Tiệc',
    '👔 Tuxedo Trắng Công Tử Bảnh Bao',
    '👔 Vest Kẻ Caro Hàn Quốc',
    '👔 Vest Màu Be Hàn Quốc Nhã Nhặn',
    '👔 Vest Nhung Đỏ Nổi Bật',
    '👔 Áo Sơ Mi Lụa Bóng Bẩy',
    '👔 Áo Sơ Mi Họa Tiết Nhiệt Đới (Hawaii)',
    '👔 Áo Polo Ralph Lauren Lịch Sự',
    '👔 Áo Thun Gucci Hàng Hiệu',
    '👔 Áo Hoodie Supreme Đường Phố',
    '👔 Áo Khoác Bomber Trẻ Trung',
    '👔 Áo Khoác Da Biker Ngầu Lòi',
    '👔 Áo Khoác Jeans Bụi Bặm Phong Trần',
    '👔 Áo Khoác Dạ Dài (Trench Coat) Hàn Quốc',
    '👔 Áo Khoác Phao Mùa Đông Ấm Áp',
    '👔 Trang Phục Lính (Military) Rằn Ri',
    '👔 Trang Phục Cảnh Sát Giao Thông',
    '👔 Trang Phục Phi Công Kính Râm',
    '👔 Trang Phục Bác Sĩ Áo Blouse',
    '👔 Trang Phục Cầu Thủ Bóng Đá Số 7',
    '👔 Trang Phục Võ Sĩ Samurai Nhật',
    '👔 Trang Phục Cao Bồi (Cowboy) Viễn Tây',
    '👔 Trang Phục Phi Hành Gia NASA',
    '👔 Trang Phục Hoàng Tử Cổ Tích',
    '👔 Trang Phục Vua Chúa Uy Quyền',
    '👔 Hanbok Nam Hàn Quốc',
    '👔 Kimono Nam Nhật Bản (Hakama)',
    '👔 Trang Phục Dân Tộc Nam Tây Bắc',
    '👔 Quần Short Đi Biển Hoa Hòe',
    '👔 Đồ Tập Gym (Tanktop) Khoe Cơ',
    '👔 Pyjama Nam Lụa Thoải Mái',
    '👔 Áo Ba Lỗ (Undershirt) Body',
    '👔 Sơ Mi Denim Bụi Phủi',
    '👔 Sơ Mi Flannel Kẻ Sọc Grunge',
    '👔 Áo Thun Trơn Basic (Minimalist)',
    '👔 Áo Len Cổ Lọ (Turtleneck) Steve Jobs',
    '👔 Set Thể Thao Adidas 3 Sọc'
];

export const FLOWERS = [
    // --- 50+ VIP TET FLOWERS ---
    'Hoa Đào Phai (Peach Blossom) Cổ Thụ',
    'Hoa Đào Bích (Red Peach) Thắm Đỏ',
    'Hoa Mai Vàng (Yellow Apricot) 5 Cánh',
    'Hoa Mai Đại Lộc (Nhiều Cánh) Phú Quý',
    'Hoa Hồng Nhung (Red Rose) Tình Yêu',
    'Hoa Sen Hồng (Lotus) Quốc Hoa',
    'Hoa Lan Hồ Điệp (Orchid) Sang Trọng',
    'Hoa Cúc Mâm Xôi (Daisy) Vàng Rực',
    'Hoa Ly (Lily) Thơm Ngát',
    'Hoa Hướng Dương (Sunflower) Mặt Trời',
    'Hoa Tulip Hà Lan Đủ Màu',
    'Hoa Cẩm Tú Cầu (Hydrangea) Đà Lạt',
    'Hoa Mẫu Đơn (Peony) Phú Quý',
    'Hoa Giấy (Bougainvillea) Rực Rỡ',
    'Hoa Phượng (Flamboyant) Vĩ',
    'Hoa Bằng Lăng Tím Thủy Chung',
    'Hoa Oải Hương (Lavender) Pháp',
    'Hoa Anh Đào (Sakura) Nhật Bản',
    'Hoa Dã Quỳ Vàng Rực Cao Nguyên',
    'Hoa Cát Tường May Mắn',
    'Hoa Đồng Tiền Tài Lộc',
    'Hoa Thủy Tiên Trắng Thanh Khiết',
    'Hoa Trà (Camellia) Kiêu Sa',
    'Hoa Thạch Thảo (Purple Aster) Tím',
    'Hoa Mimosa Vàng Đà Lạt',
    'Hoa Cải Vàng Mộc Châu',
    'Hoa Tam Giác Mạch Hà Giang',
    'Hoa Ban Trắng Tây Bắc',
    'Hoa Mận Trắng Sơn La',
    'Hoa Gạo Đỏ Làng Quê',
    'Hoa Súng Đồng Tháp Mười',
    'Hoa Mười Giờ Khoe Sắc',
    'Hoa Lay Ơn (Gladiolus) Đỏ',
    'Hoa Thược Dược Muôn Màu',
    'Hoa Hải Đường Đỏ Thắm',
    'Hoa Tầm Xuân Nụ Xanh',
    'Hoa Trạng Nguyên Đỏ Rực',
    'Hoa Đỗ Quyên Rừng',
    'Hoa Nhài Thơm Ngát',
    'Hoa Quỳnh Nở Đêm',
    'Hoa Sen Đá (Succulent)',
    'Hoa Xương Rồng Nở Hoa',
    'Hoa Bỉ Ngạn Đỏ Bí Ẩn',
    'Hoa Tuyết Điểm (Snowdrop)',
    'Hoa Diên Vỹ (Iris)',
    'Hoa Tử Đằng (Wisteria) Tím Rủ',
    'Hoa Mộc Lan (Magnolia)',
    'Hoa Sữa Hà Nội',
    'Hoa Hoàng Yến (Bọ Cạp Vàng)',
    'Hoa Chuông Vàng'
];

export const DESTINATIONS = [
    // --- 50+ VIP TET DESTINATIONS ---
    'Hồ Gươm Hà Nội (Tháp Rùa) Ngày Tết',
    'Phố Cổ Hội An Đèn Lồng Đêm Rằm',
    'Vịnh Hạ Long Du Thuyền 5 Sao',
    'Cầu Vàng Đà Nẵng (Bàn Tay Phật)',
    'Đà Lạt Thành Phố Ngàn Hoa Xuân',
    'Sapa Đỉnh Fansipan Tuyết Phủ',
    'Tràng An Ninh Bình Non Nước',
    'Cố Đô Huế Đại Nội Uy Nghi',
    'Chợ Bến Thành Sài Gòn Nhộn Nhịp',
    'Phú Quốc Đảo Ngọc Sunset Sanato',
    'Tháp Eiffel Paris Pháo Hoa Giao Thừa',
    'Núi Phú Sĩ Nhật Bản Hoa Anh Đào',
    'Vạn Lý Trường Thành Trung Quốc',
    'Tượng Nữ Thần Tự Do New York',
    'Nhà Hát Opera Sydney Úc',
    'Tháp Nghiêng Pisa Ý',
    'Kim Tự Tháp Ai Cập Cưỡi Lạc Đà',
    'Dubai Burj Khalifa Tòa Nhà Cao Nhất',
    'Santorini Hy Lạp Nhà Trắng Mái Xanh',
    'Maldives Resort Trên Biển',
    'Quảng Trường Đỏ Moscow Nga',
    'Taj Mahal Ấn Độ Lăng Mộ Đẹp Nhất',
    'Đấu Trường La Mã Rome Ý',
    'Bali Indonesia Cổng Trời',
    'Rio de Janeiro Brazil Tượng Chúa',
    'Thác Niagara Canada Hùng Vĩ',
    'Cánh Đồng Cối Xay Gió Hà Lan Tulip',
    'Lâu Đài Neuschwanstein Đức Cổ Tích',
    'Phượng Hoàng Cổ Trấn Trung Quốc',
    'Kyoto Nhật Bản Chùa Vàng',
    'Cầu Cổng Vàng San Francisco Mỹ',
    'Tháp Big Ben London Anh',
    'Quảng Trường Thời Đại Times Square NYC',
    'Vườn Bay Gardens by the Bay Singapore',
    'Tháp Đôi Petronas Malaysia',
    'Chùa Shwedagon Myanmar Vàng Rực',
    'Angkor Wat Campuchia Bí Ẩn',
    'Đảo Jeju Hàn Quốc Mùa Xuân',
    'Vườn Quốc Gia Yellowstone Mỹ',
    'Hẻm Núi Grand Canyon Mỹ',
    'Thành Phố Venice Ý Kênh Đào',
    'Thành Phố Barcelona Tây Ban Nha',
    'Thành Phố Istanbul Thổ Nhĩ Kỳ',
    'Thành Phố Petra Jordan',
    'Thành Phố Machu Picchu Peru',
    'Đảo Bora Bora Polynesia',
    'Quần Đảo Hawaii Mỹ',
    'Đảo Fiji Thiên Đường',
    'Đảo Seychelles Châu Phi',
    'Nam Cực Băng Giá Chim Cánh Cụt'
];

export const FAMILY_CONCEPTS = [
    // --- 50+ VIP FAMILY TET REUNION CONCEPTS (STRICTLY VIETNAM) ---
    'Gia Đình Sum Vầy Bên Mâm Cơm Tất Niên Chiều 30',
    'Đại Gia Đình Tam Đại Đồng Đường Chúc Tết Ông Bà',
    'Cả Nhà Quây Quần Gói Bánh Chưng Bên Bếp Lửa Hồng',
    'Khoảnh Khắc Lì Xì Đầu Năm Cười Rạng Rỡ',
    'Gia Đình Du Xuân Văn Miếu Quốc Tử Giám Xin Chữ',
    'Chụp Ảnh Gia Đình Tại Đường Hoa Nguyễn Huệ Rực Rỡ',
    'Gia Đình Dạo Bước Phố Cổ Hội An Đêm Đèn Lồng',
    'Cả Nhà Đi Lễ Chùa Hương Cầu Bình An',
    'Gia Đình Thăm Mộ Tổ Tiên Ngày Cuối Năm',
    'Bữa Cơm Đoàn Viên Mùng 1 Tết Ấm Cúng',
    'Gia Đình Mặc Áo Dài Truyền Thống Chụp Ảnh Tết',
    'Ông Bà Kể Chuyện Cổ Tích Cho Cháu Nghe',
    'Gia Đình Cùng Nhau Trang Trí Cây Đào/Mai',
    'Khoảnh Khắc Giao Thừa Cùng Xem Pháo Hoa',
    'Gia Đình Du Lịch Đà Lạt Ngắm Hoa Xuân',
    'Cả Nhà Thưởng Thức Trà Sen Mứt Tết',
    'Gia Đình Đi Chợ Hoa Hàng Lược Sắm Tết',
    'Đại Gia Đình Chụp Ảnh Kỷ Niệm Trước Cổng Nhà Cổ',
    'Gia Đình Sum Họp Bên Mâm Ngũ Quả',
    'Cháu Chúc Thọ Ông Bà Nhận Lì Xì Đỏ',
    'Gia Đình Đi Thuyền Trên Sông Hương Nghe Ca Huế',
    'Cả Nhà Cùng Nhau Dọn Dẹp Nhà Cửa Đón Tết',
    'Gia Đình Thăm Hỏi Chúc Tết Họ Hàng',
    'Khoảnh Khắc Cả Nhà Cười Vui Xem Táo Quân',
    'Gia Đình Thả Cá Chép Tiễn Ông Táo Về Trời',
    'Gia Đình Dạo Chơi Hồ Gươm Sáng Mùng 1',
    'Cả Nhà Cùng Nhau Nấu Cỗ Cúng Gia Tiên',
    'Gia Đình Du Xuân Tràng An Ninh Bình',
    'Gia Đình Chụp Ảnh Tại Vườn Đào Nhật Tân',
    'Khoảnh Khắc Bé Nhận Bao Lì Xì Đầu Tiên',
    'Gia Đình Sum Vầy Trong Phòng Khách Sang Trọng',
    'Gia Đình Du Lịch Phú Quốc Nghỉ Dưỡng Tết',
    'Cả Nhà Cùng Nhau Hát Karaoke Xuân',
    'Gia Đình Chơi Bài Vui Vẻ Ngày Tết (Bầu Cua)',
    'Gia Đình Đi Chợ Nổi Cái Răng Sắm Hoa',
    'Gia Đình Thăm Làng Gốm Bát Tràng Dịp Xuân',
    'Cả Nhà Cùng Nhau Viết Câu Đối Đỏ',
    'Gia Đình Thưởng Thức Bánh Chưng Dưa Hành',
    'Gia Đình Đi Lễ Đền Hùng Phú Thọ',
    'Khoảnh Khắc Vợ Chồng Trao Nhau Nụ Hôn Xuân',
    'Gia Đình Cùng Nhau Xem Múa Lân Sư Rồng',
    'Gia Đình Thăm Nhà Thờ Đức Bà Sài Gòn',
    'Cả Nhà Cùng Nhau Chơi Trò Chơi Dân Gian',
    'Gia Đình Du Xuân Yên Tử Quảng Ninh',
    'Gia Đình Cùng Nhau Đi Hái Lộc Đầu Năm',
    'Gia Đình Thưởng Thức Cà Phê Sáng Mùng 1',
    'Gia Đình Sum Vầy Bên Cây Quất Trĩu Quả',
    'Cả Nhà Cùng Nhau Chụp Ảnh Selfie Tết',
    'Gia Đình Tứ Đại Đồng Đường Hạnh Phúc',
    'Gia Đình Cùng Nhau Nâng Ly Rượu Mừng Xuân',
    'Khoảnh Khắc Bình Yên Sáng Mùng 1 Tết',
    'Gia Đình Dạo Biển Nha Trang Ngày Xuân',
    'Gia Đình Chụp Ảnh Kỷ Niệm Tại Cầu Vàng',
    'Cả Nhà Cùng Nhau Làm Mứt Tết Cổ Truyền'
];

export const TRAVEL_CONCEPTS = [
    // --- 50+ VIP TRAVEL CONCEPTS ---
    'Check-in Resort 6 Sao Sang Chảnh Mùa Tết',
    'Phượt Thủ (Bụi Bặm) Khám Phá Tây Bắc Mùa Xuân',
    'Khám Phá Di Sản Văn Hóa Cố Đô Huế',
    'Nghỉ Dưỡng Biển Nhiệt Đới (Tropical) Phú Quốc',
    'Leo Núi Săn Mây Tà Xùa Ngày Tết',
    'Cắm Trại (Camping) Bên Hồ Tuyền Lâm',
    'Roadtrip Xe Mui Trần Dọc Bờ Biển',
    'Du Thuyền 5 Sao Hạ Long Đón Giao Thừa',
    'Trượt Tuyết (Winter) Sapa Mùa Đông',
    'Lặn Biển (Scuba Diving) Ngắm San Hô Tết',
    'Bay Dù Lượn (Paragliding) Mù Cang Chải',
    'Khinh Khí Cầu (Cappadocia) Ngắm Bình Minh',
    'Thám Hiểm Rừng Rậm (Amazon) Bí Ẩn',
    'Cưỡi Lạc Đà Sa Mạc Sahara Đón Xuân',
    'Săn Bắc Cực Quang (Aurora) Iceland',
    'Lễ Hội Carnival Rio De Janeiro Sôi Động',
    'Thưởng Thức Trà Chiều London Quý Tộc',
    'Mua Sắm Hàng Hiệu Paris (Shopping)',
    'Thiền Định Tây Tạng Cầu Bình An',
    'Safari Châu Phi Ngắm Động Vật Hoang Dã',
    'Du Lịch Vũ Trụ (Space Tourism) Tương Lai',
    'Du Lịch Tâm Linh Chùa Bái Đính',
    'Du Lịch Ẩm Thực Đường Phố Hà Nội',
    'Du Lịch Sông Nước Miền Tây Chợ Nổi',
    'Du Lịch Đảo Lý Sơn Hoang Sơ',
    'Du Lịch Côn Đảo Linh Thiêng',
    'Du Lịch Mũi Né Đồi Cát Bay',
    'Du Lịch Phong Nha Kẻ Bàng Thám Hiểm',
    'Du Lịch Đà Nẵng Thành Phố Đáng Sống',
    'Du Lịch Nha Trang Biển Xanh Cát Trắng',
    'Du Lịch Vũng Tàu Cuối Tuần',
    'Du Lịch Tam Đảo Mờ Sương',
    'Du Lịch Mộc Châu Mùa Hoa Cải',
    'Du Lịch Hà Giang Mùa Tam Giác Mạch',
    'Du Lịch Cao Bằng Thác Bản Giốc',
    'Du Lịch Lạng Sơn Mẫu Sơn Tuyết',
    'Du Lịch Yên Bái Ruộng Bậc Thang',
    'Du Lịch Bắc Ninh Hội Lim Quan Họ',
    'Du Lịch Ninh Bình Tràng An Bái Đính',
    'Du Lịch Thanh Hóa Sầm Sơn',
    'Du Lịch Nghệ An Cửa Lò Quê Bác',
    'Du Lịch Quảng Bình Hang Sơn Đoòng',
    'Du Lịch Quảng Trị Thành Cổ',
    'Du Lịch Quảng Nam Phố Cổ Hội An',
    'Du Lịch Bình Định Quy Nhơn Kỳ Co',
    'Du Lịch Phú Yên Hoa Vàng Cỏ Xanh',
    'Du Lịch Khánh Hòa Đảo Bình Ba',
    'Du Lịch Ninh Thuận Vườn Nho',
    'Du Lịch Bình Thuận Mũi Né',
    'Du Lịch Đồng Tháp Mùa Nước Nổi'
];

export const CAMERA_ANGLES = [
    // --- 50+ VIP CAMERA ANGLES ---
    'Góc chính diện (Front) Chân Dung',
    'Góc nghiêng 45 độ (Side) Thần Thánh',
    'Góc từ dưới lên (Low Angle) Quyền Lực',
    'Góc từ trên xuống (High Angle) Dễ Thương',
    'Cận cảnh (Close-up) Focus Mắt/Môi',
    'Trung cảnh (Medium Shot) Nửa Người',
    'Toàn cảnh (Wide Shot) Lấy Cả Bối Cảnh',
    'Góc nhìn qua vai (Over-shoulder) Bí Ẩn',
    'Góc mắt cá (Fisheye) Nghệ Thuật',
    'Góc flycam (Drone) Toàn Cảnh Từ Cao',
    'Góc nhìn thứ nhất (POV) Trải Nghiệm',
    'Góc nghiêng Dutch Angle Kịch Tính',
    'Góc chụp Macro (Chi tiết) Nhụy Hoa/Trang Sức',
    'Góc chụp Panorama (Toàn cảnh rộng) Phong Cảnh',
    'Góc chụp Reflection (Phản chiếu) Qua Gương/Nước',
    'Góc chụp Silhouette (Ngược sáng) Bóng Đen',
    'Góc chụp Bokeh (Xóa phông) Mờ Ảo',
    'Góc chụp Motion Blur (Chuyển động) Tốc Độ',
    'Góc chụp Top-down (Flatlay) Sắp Đặt Đồ Vật',
    'Góc chụp Tắt đèn (Low Key) Tương Phản Cao',
    'Góc chụp Sáng Chói (High Key) Trong Trẻo',
    'Góc chụp Eye-level (Ngang tầm mắt) Tự Nhiên',
    'Góc chụp Worm\'s-eye (Mắt sâu) Sát Đất',
    'Góc chụp Bird\'s-eye (Mắt chim) Vuông Góc Từ Trên',
    'Góc chụp 3/4 (Three-quarter) Kinh Điển',
    'Góc chụp Profile (Góc nghiêng hoàn toàn)',
    'Góc chụp Back view (Sau lưng) So Deep',
    'Góc chụp Action (Hành động) Bắt Khoảnh Khắc',
    'Góc chụp Candid (Lén) Tự Nhiên Không Diễn',
    'Góc chụp Framed (Khung trong khung)',
    'Góc chụp Leading Lines (Đường dẫn)',
    'Góc chụp Symmetry (Đối xứng) Hoàn Hảo',
    'Góc chụp Rule of Thirds (Quy tắc 1/3)',
    'Góc chụp Negative Space (Không gian âm)',
    'Góc chụp Fill the Frame (Lấp đầy khung hình)',
    'Góc chụp Golden Ratio (Tỷ lệ vàng)',
    'Góc chụp Diagonal (Đường chéo) Năng Động',
    'Góc chụp Triangle (Tam giác) Cân Bằng',
    'Góc chụp Pattern (Họa tiết) Lặp Lại',
    'Góc chụp Texture (Bề mặt) Chi Tiết',
    'Góc chụp Minimalism (Tối giản)',
    'Góc chụp Maximalism (Tối đa) Nhiều Chi Tiết',
    'Góc chụp Abstract (Trừu tượng)',
    'Góc chụp Surreal (Siêu thực)',
    'Góc chụp Vintage (Cổ điển)',
    'Góc chụp Documentary (Tài liệu)',
    'Góc chụp Fashion (Thời trang)',
    'Góc chụp Street (Đường phố)',
    'Góc chụp Architecture (Kiến trúc)',
    'Góc chụp Food (Ẩm thực)'
];

export const STUDIO_CONCEPTS = [
    // --- 50+ VIP STUDIO CONCEPTS ---
    'Studio Phông Đỏ (Tết) Truyền Thống',
    'Studio Phông Trắng (Minimalist) Hiện Đại',
    'Studio Phông Đen (Huyền bí) Sang Trọng',
    'Studio Hoa Nghệ Thuật (Floral) Rực Rỡ',
    'Studio Ánh Sáng Neon (Cyberpunk) Tương Lai',
    'Studio Cổ Điển (Vintage) Hoài Niệm',
    'Studio Thiên Nhiên (Indoor Garden) Xanh Mát',
    'Studio Sang Trọng (Luxury Furniture) Hoàng Gia',
    'Studio Trừu Tượng (Abstract) Nghệ Thuật',
    'Studio Thời Trang (High Fashion) Vogue',
    'Studio Cyberpunk (Tương lai) Đèn Led',
    'Studio Retro Pop Art (Thập niên 80)',
    'Studio Giấy Dó (Truyền thống) Dân Gian',
    'Studio Bóng Bay (Sinh nhật/Tiệc Tùng)',
    'Studio Mây Khói (Dreamy) Bồng Bềnh',
    'Studio Gương Phản Chiếu (Reflection) Vô Cực',
    'Studio Nước (Underwater Effect) Dưới Nước',
    'Studio Lửa (Fire Effect) Ấm Áp',
    'Studio Băng Tuyết (Ice Queen) Mát Lạnh',
    'Studio Dát Vàng (Gold Leaf) Vương Giả',
    'Studio Lụa Bay (Flying Silk) Mềm Mại',
    'Studio Hoa Khô (Dried Flowers) Vintage',
    'Studio Sách (Library) Tri Thức',
    'Studio Tranh Vẽ (Painting) Họa Sĩ',
    'Studio Nhạc Cụ (Music) Nghệ Sĩ',
    'Studio Bếp (Kitchen) Nấu Ăn',
    'Studio Giường Ngủ (Bedroom) Ấm Cúng',
    'Studio Bồn Tắm (Bathtub) Thư Giãn',
    'Studio Cửa Sổ (Window) Nắng Sớm',
    'Studio Cầu Thang (Stairs) Xoắn Ốc',
    'Studio Tường Gạch (Brick Wall) Loft',
    'Studio Bê Tông (Concrete) Industrial',
    'Studio Gỗ (Wood) Rustic',
    'Studio Kim Loại (Metal) Sắc Lạnh',
    'Studio Kính (Glass) Trong Suốt',
    'Studio Vải Nhung (Velvet) Quý Phái',
    'Studio Lông Vũ (Feather) Nhẹ Nhàng',
    'Studio Phấn Màu (Pastel) Ngọt Ngào',
    'Studio Đơn Sắc (Monochrome) Tinh Tế',
    'Studio Graffiti (Street Art) Bụi Bặm',
    'Studio Phim Trường (Movie Set) Điện Ảnh',
    'Studio Sân Khấu (Stage) Biểu Diễn',
    'Studio Rạp Xiếc (Circus) Vui Nhộn',
    'Studio Lồng Chim (Birdcage) Lãng Mạn',
    'Studio Xích Đu (Swing) Tuổi Thơ',
    'Studio Ghế Sofa (Chesterfield) Cổ Điển',
    'Studio Đèn Chùm (Chandelier) Lộng Lẫy',
    'Studio Nến (Candle) Lãng Mạn',
    'Studio Rèm Cửa (Curtain) Bí Ẩn',
    'Studio Thảm Đỏ (Red Carpet) Sự Kiện'
];

export const ROYAL_CONCEPTS = [
    // --- 50+ VIP ROYAL CONCEPTS (TET) ---
    'Hoàng Gia Việt Nam (Nhà Nguyễn) Đón Tết',
    'Hoàng Gia Anh Quốc (Windsor) Tiệc Trà Xuân',
    'Hoàng Gia Châu Âu (Cổ tích) Lâu Đài Tết',
    'Hoàng Gia Trung Hoa (Tử Cấm Thành) Đèn Lồng',
    'Hoàng Gia Nhật Bản (Edo) Hoa Anh Đào',
    'Hoàng Gia Thái Lan (Golden) Chùa Vàng',
    'Hoàng Gia Ai Cập (Pharaoh) Sông Nile',
    'Nữ Hoàng Băng Giá (Elsa) Cung Điện Băng',
    'Vua Mặt Trời (Louis XIV) Cung Điện Versailles',
    'Công Chúa/Hoàng Tử Disney Dự Tiệc',
    'Hoàng Đế La Mã (Roman) Đấu Trường',
    'Nữ Hoàng Victoria (Cổ điển) Anh Quốc',
    'Hoàng Gia Nga (Sa Hoàng) Mùa Đông',
    'Vua Midas (Chạm tay hóa vàng) Kho Báu',
    'Nữ Hoàng Cleopatra Ai Cập Huyền Bí',
    'Vua Arthur & Hiệp sĩ bàn tròn',
    'Công Chúa Ba Tư (Nghìn Lẻ Một Đêm)',
    'Hoàng Hậu Nam Phương (Áo Dài Gấm)',
    'Vua Bảo Đại (Âu Phục Sang Trọng)',
    'Hoàng Gia Dubai (Hiện đại) Siêu Xe',
    'Cung Điện Versailles Pháp Lộng Lẫy',
    'Cung Điện Mùa Đông Nga Tuyết Trắng',
    'Ngai Vàng Sắt (Game of Thrones) Quyền Lực',
    'Lễ Đăng Quang (Coronation) Nhà Vua',
    'Tiệc Trà Hoàng Gia (Royal Tea Party)',
    'Dạ Hội Cung Đình (Royal Ball) Khiêu Vũ',
    'Công Chúa Ngủ Trong Rừng (Sleeping Beauty)',
    'Hoàng Tử Ếch (Frog Prince)',
    'Công Chúa Tóc Mây (Rapunzel)',
    'Nữ Hoàng Đỏ (Alice in Wonderland)',
    'Vua Biển Cả (Aquaman) Cung Điện Nước',
    'Nữ Thần Chiến Binh (Wonder Woman)',
    'Hoàng Đế Napoleon Pháp',
    'Nữ Hoàng Elizabeth Anh',
    'Hoàng Thái Hậu Từ Dụ',
    'Vua Quang Trung Áo Bào Đỏ',
    'Công Chúa Ngọc Hân',
    'Lễ Hội Hoa Đăng Cung Đình',
    'Ngự Thiện Phòng (Bếp Hoàng Gia)',
    'Ngự Hoa Viên (Vườn Hoàng Gia)',
    'Thái Y Viện (Bác Sĩ Hoàng Gia)',
    'Khâm Thiên Giám (Chiêm Tinh)',
    'Vệ Binh Hoàng Gia Anh',
    'Kỵ Sĩ Hoàng Gia Giáp Sắt',
    'Xe Ngựa Bí Ngô Hoàng Gia',
    'Du Thuyền Hoàng Gia',
    'Chuyên Cơ Hoàng Gia',
    'Biệt Thự Mùa Hè Hoàng Gia',
    'Lâu Đài Cát Hoàng Gia Biển',
    'Vương Miện Kim Cương Hoàng Gia'
];

export const EMERALD_CONCEPTS = [
    // --- 50+ VIP RUSTIC/COUNTRY/OLD TET CONCEPTS (UPDATED) ---
    'Phiên Chợ Tết Quê Xưa Nhộn Nhịp',
    'Gánh Hàng Hoa Tết Bên Đường Làng',
    'Nồi Bánh Chưng Bếp Lửa Hồng Đêm 30',
    'Ông Đồ Cho Chữ Thư Pháp Ngày Xuân',
    'Múa Lân Sư Rồng Sân Đình Làng',
    'Cây Đa Bến Nước Sân Đình Ngày Tết',
    'Nhà Tranh Vách Đất Mái Lá Đơn Sơ',
    'Ruộng Bậc Thang Mù Cang Chải Mùa Xuân',
    'Cánh Đồng Lúa Chín Vàng Mùa Gặt Tết',
    'Con Trâu Đi Cày Ruộng Mùa Xuân',
    'Lũy Tre Làng Xanh Mát Yên Bình',
    'Ao Sen Làng Quê Nở Hoa Thơm Ngát',
    'Cầu Khỉ Miền Tây Sông Nước',
    'Chợ Nổi Cái Răng Ghe Thuyền Tấp Nập',
    'Vườn Rau Ao Cá Vui Thú Điền Viên',
    'Bếp Củi Tro Than Nướng Khoai Ngô',
    'Mâm Cơm Tất Niên Quê Nhà Đơn Giản',
    'Trẻ Em Chơi Đánh Quay Nhảy Dây',
    'Bà Cụ Nhai Trầu Kể Chuyện Cổ Tích',
    'Thiếu Nữ Mặc Yếm Đào Bên Hoa Sen',
    'Chàng Trai Chăn Trâu Thổi Sáo',
    'Làng Nghề Làm Gốm Bát Tràng',
    'Làng Nghề Dệt Lụa Vạn Phúc',
    'Làng Nghề Làm Nón Lá Chuông',
    'Làng Nghề Làm Tranh Đông Hồ',
    'Làng Nghề Làm Hương (Nhang) Đỏ Rực',
    'Làng Nghề Làm Đèn Lồng Hội An',
    'Làng Nghề Làm Quạt Giấy Chàng Sơn',
    'Làng Nghề Đúc Đồng Ngũ Xã',
    'Làng Nghề Mộc Kim Bồng',
    'Vườn Cây Ăn Trái Miền Tây Trĩu Quả',
    'Rừng Cọ Đồi Chè Thái Nguyên Xanh Ngát',
    'Thung Lũng Hoa Mận Trắng Mộc Châu',
    'Đồi Thông Đà Lạt Sương Mù',
    'Biển Lúa Vàng Tam Cốc Ninh Bình',
    'Chùa Hương Tấp Nập Người Đi Lễ',
    'Đền Hùng Phú Thọ Dịp Giỗ Tổ',
    'Hội Lim Bắc Ninh Hát Quan Họ',
    'Lễ Hội Chọi Trâu Đồ Sơn',
    'Lễ Hội Đua Thuyền Sông Nước',
    'Đêm Trăng Rằm Làng Quê Yên Tĩnh',
    'Tiếng Gà Gáy Sáng Đánh Thức Làng Quê',
    'Khói Lam Chiều Tỏa Trên Mái Tranh',
    'Giếng Nước Gốc Đa Đầu Làng',
    'Đình Làng Mái Ngói Rêu Phong',
    'Cổng Làng Cổ Kính Uy Nghiêm',
    'Đường Làng Lát Gạch Đỏ',
    'Hàng Cau Thẳng Tắp Trước Sân',
    'Vại Nước Mưa Chum Sành',
    'Cối Đá Xay Bột Làm Bánh'
];

export const BILLIONAIRE_CONCEPTS = [
    // --- 50+ VIP BILLIONAIRE CONCEPTS (TET) ---
    'Tiệc Tất Niên Trên Du Thuyền 5 Sao',
    'Chuyên Cơ Riêng (Private Jet) Chở Đào Mai',
    'Biệt Thự Dát Vàng Đón Giao Thừa',
    'Siêu Xe Thể Thao Chở Quà Tết',
    'Mua Sắm Hàng Hiệu (Shopping Spree) Paris',
    'Bữa Tối Sang Trọng (Fine Dining) Michelin',
    'Sòng Bạc Casino Monte Carlo Thử Vận May',
    'Thảm Đỏ Sự Kiện (Red Carpet) Gala Cuối Năm',
    'Văn Phòng CEO View City Landmark 81',
    'Kho Tiền Vàng (Money Vault) Đầy Ắp Lì Xì',
    'Đảo Tư Nhân (Private Island) Nghỉ Tết',
    'Du Lịch Vũ Trụ (SpaceX) Ngắm Pháo Hoa',
    'Bộ Sưu Tập Đồng Hồ Patek Philippe Tiền Tỷ',
    'Hầm Rượu Vang Triệu Đô Khai Tiệc',
    'Sân Golf Hoàng Gia Đánh Golf Đầu Xuân',
    'Tiệc Hồ Bơi Đón Giao Thừa (Pool Party)',
    'Lái Trực Thăng Cá Nhân Du Xuân',
    'Sở Hữu Đội Bóng Đá Ngoại Hạng Anh',
    'Kỳ Nghỉ Tết Tại Resort Maldives',
    'Penthouse New York View Times Square',
    'Dinh Thự Beverly Hills Hollywood',
    'Siêu Du Thuyền Monaco Grand Prix',
    'Tiệc Cocktail Tầng Thượng Rooftop Bar',
    'Giao Dịch Chứng Khoán Wall Street Hái Lộc',
    'Ký Hợp Đồng Tỷ Đô Khai Xuân',
    'Chụp Ảnh Bìa Tạp Chí Forbes Vietnam',
    'Sở Hữu Vườn Thượng Uyển Riêng',
    'Bể Bơi Vô Cực Dát Vàng',
    'Phòng Chiếu Phim Tại Gia IMAX',
    'Spa Tại Gia (Home Spa) Thư Giãn',
    'Phòng Gym Cá Nhân Công Nghệ Cao',
    'Thư Viện Sách Cổ Quý Hiếm',
    'Garage Siêu Xe (Car Collection) Đầy Ắp',
    'Hồ Cá Koi Nhật Bản Tiền Tỷ',
    'Vườn Lan Đột Biến Gen Quý Hiếm',
    'Nuôi Thú Cưng Độc Lạ (Hổ, Sư Tử)',
    'Vệ Sĩ Riêng Mặc Vest Đen',
    'Quản Gia Anh Quốc Phục Vụ',
    'Đầu Bếp Riêng Nấu Món Tết',
    'Tiệc Rượu Champagne Tháp Ly',
    'Mưa Tiền Đô La (Money Rain)',
    'Tắm Trong Bồn Tiền Vàng',
    'Ngủ Trên Giường Tiền',
    'Đi Mua Sắm Bằng Trực Thăng',
    'Thuê Nguyên Công Viên Disney',
    'Bắn Pháo Hoa Riêng Tại Gia',
    'Tặng Siêu Xe Cho Người Yêu',
    'Lì Xì Bằng Sổ Đỏ/Kim Cương',
    'Ăn Bánh Chưng Dát Vàng 24K',
    'Uống Trà Trong Chén Ngọc Cổ'
];

export const HEAVENLY_CONCEPTS = [
    // --- 50+ VIP HEAVENLY CONCEPTS (TET) ---
    'Tiên Cảnh Bồng Lai Đón Xuân',
    'Cổng Trời (Heaven Gate) Mở Ra Năm Mới',
    'Đám Mây Ngũ Sắc (Tường Vân) May Mắn',
    'Thiên Thần Cánh Trắng Chúc Phúc',
    'Cung Điện Trên Mây (Cloud Palace)',
    'Cầu Vồng Đôi Rực Rỡ Sau Mưa Xuân',
    'Ánh Sáng Thần Thánh (God Rays) Soi Rọi',
    'Hoa Sen Tỏa Sáng Hào Quang',
    'Hồ Nước Tiên (Fairy Lake) Trong Vắt',
    'Bay Lượn Giữa Không Trung Như Tiên',
    'Thần Thoại Hy Lạp (Olympus) Dự Tiệc',
    'Cung Quảng Hàn (Chị Hằng) Ngắm Trăng',
    'Thiên Đường Eden (Vườn Địa Đàng)',
    'Thác Nước Vô Cực (Infinity Waterfall)',
    'Cánh Đồng Hoa Bất Tử (Immortal Flowers)',
    'Lâu Đài Pha Lê (Crystal Castle)',
    'Thần Vệ Nữ (Venus) Sắc Đẹp',
    'Thiên Thần Tình Yêu (Cupid) Bắn Cung',
    'Pegasus (Ngựa Thần) Có Cánh',
    'Phượng Hoàng Lửa Tái Sinh (Reborn)',
    'Rồng Thần Cuộn Mây (Shenron)',
    'Tiên Nữ Winx Phép Thuật',
    'Thủy Thủ Mặt Trăng (Sailor Moon)',
    'Nữ Thần Tự Do (Fantasy Ver) Cầm Đuốc',
    'Thần Tài Gõ Cửa Ban Lộc',
    'Ông Thọ Ban Tuổi Thọ',
    'Ông Lộc Ban Tiền Tài',
    'Ông Phúc Ban Hạnh Phúc',
    'Phật Bà Quan Âm Cam Lộ',
    'Chúa Giêsu Ban Phước Lành',
    'Đức Mẹ Maria Hiền Từ',
    'Thiên Thần Hộ Mệnh (Guardian Angel)',
    'Tinh Tú (Stars) Lấp Lánh',
    'Vũ Trụ (Galaxy) Bao La',
    'Hố Đen (Black Hole) Huyền Bí',
    'Sao Băng (Shooting Star) Ước Nguyện',
    'Mặt Trăng (Moon) Tròn Vành Vạnh',
    'Mặt Trời (Sun) Rực Rỡ',
    'Các Vì Sao (Zodiac) Chiêm Tinh',
    'Cung Hoàng Đạo (Horoscope)',
    'Thần Rừng (Forest Spirit)',
    'Thần Biển (Ocean Spirit)',
    'Thần Núi (Mountain Spirit)',
    'Thần Gió (Wind Spirit)',
    'Thần Lửa (Fire Spirit)',
    'Thần Sấm (Thunder Spirit)',
    'Thần Mưa (Rain Spirit)',
    'Nàng Tiên Cá (Mermaid) Hát Ca',
    'Yêu Tinh (Elf) Rừng Xanh',
    'Người Khổng Lồ (Giant) Hiền Lành'
];

export const ZODIAC_HORSE_CONCEPTS = [
    // --- 50+ VIP HORSE CONCEPTS (2026) ---
    'Ngựa Vàng May Mắn (Golden Horse) 2026',
    'Chiến Mã Oai Phong Ra Trận',
    'Ngựa Thần Pegasus Có Cánh Trắng',
    'Ngựa Một Sừng (Unicorn) Phép Thuật',
    'Ngựa Xích Thố (Red Hare) Quan Vũ',
    'Xe Ngựa Bí Ngô (Cinderella) Cổ Tích',
    'Đua Ngựa Hoàng Gia (Royal Ascot)',
    'Cao Bồi Viễn Tây (Cowboy) Cưỡi Ngựa',
    'Ngựa Gỗ Tuổi Thơ (Rocking Horse)',
    'Ngựa Đá Cổ Đại (Stone Horse)',
    'Ngựa Máy Cơ Khí (Steampunk Horse)',
    'Ngựa Lửa (Nightmare) Rực Cháy',
    'Ngựa Băng (Ice Horse) Lạnh Giá',
    'Ngựa Biển (Seahorse Fantasy) Đại Dương',
    'Ngựa Vằn Nghệ Thuật (Zebra Art)',
    'Nhân Mã (Centaur) Thần Thoại',
    'Kỵ Sĩ Bóng Đêm (Dark Knight)',
    'Ngựa Hoang Thảo Nguyên Mông Cổ',
    'Ngựa Xiếc (Circus Horse) Biểu Diễn',
    'Ngựa Troia (Trojan Horse) Gỗ Khổng Lồ',
    'Thần Mã Thánh Gióng Bay Về Trời',
    'Ngựa Bạch Tuyết (White Horse) Hoàng Tử',
    'Ngựa Đen Tuyệt Đẹp (Black Beauty)',
    'Ngựa Pony Dễ Thương (My Little Pony)',
    'Vua Của Các Loài Ngựa (Horse King)',
    'Ngựa Thồ Hàng Tết Về Bản',
    'Ngựa Kéo Xe Hoa Đám Cưới',
    'Ngựa Cảnh Sát Tuần Tra',
    'Ngựa Đua F1 Tốc Độ',
    'Ngựa Robot Tương Lai',
    'Ngựa Giấy Cúng Táo Quân',
    'Ngựa Mây (Cloud Horse)',
    'Ngựa Sao (Star Horse)',
    'Ngựa Hoa (Flower Horse)',
    'Ngựa Kim Cương (Diamond Horse)',
    'Ngựa Ngọc Bích (Jade Horse)',
    'Ngựa Vàng 24K (Gold Statue)',
    'Ngựa Sứ Bát Tràng',
    'Ngựa Gỗ Đồ Chơi',
    'Ngựa Quay (Carousel) Công Viên',
    'Ngựa Chiến Trung Cổ Giáp Sắt',
    'Ngựa Thồ Rượu Vang',
    'Ngựa Kéo Xe Trượt Tuyết',
    'Ngựa Của Zorro (Tornado)',
    'Ngựa Của Lucky Luke (Jolly Jumper)',
    'Ngựa Thần Mặt Trời',
    'Ngựa Thần Gió',
    'Ngựa Thần Sấm Sét',
    'Đàn Ngựa Phi Nước Đại (Mã Đáo Thành Công)',
    'Cặp Ngựa Uyên Ương (Couple Horses)'
];

export const FASHION_STUDIO_CONCEPTS = [
    // --- 50+ VIP FASHION CONCEPTS (TET) ---
    'Sàn Diễn Runway Paris Tuần Lễ Thời Trang Tết',
    'Bìa Tạp Chí Vogue Vietnam Số Tết',
    'Street Style New York Đường Phố Mùa Xuân',
    'Haute Couture (Cao cấp) Dạ Hội Tết',
    'Avant-Garde (Phá cách) Thời Trang Tương Lai',
    'Retro Fashion 80s (Disco) Sôi Động',
    'Cyberpunk Fashion (Techwear) Năm 2077',
    'Bohemian Style (Du mục) Phóng Khoáng',
    'Minimalist Fashion (Tối giản) Sang Trọng',
    'Gothic Lolita (Huyền bí) Quyến Rũ',
    'Vintage 1920s (Gatsby) Dạ Tiệc Thượng Lưu',
    'Y2K Fashion (2000s) Gen Z Cá Tính',
    'Cottagecore (Đồng quê) Nàng Thơ',
    'Dark Academia (Học đường) Quý Tộc',
    'Streetwear Hypebeast (Supreme/Off-White)',
    'Business Chic (Doanh nhân) Thành Đạt',
    'Bridal Couture (Váy cưới) Lộng Lẫy',
    'Met Gala (Thảm đỏ) Trang Phục Độc Lạ',
    'Coachella (Lễ hội âm nhạc) Mùa Xuân',
    'Harajuku (Nhật Bản) Đầy Màu Sắc',
    'K-Pop Idol Style (Blackpink/BTS) Sân Khấu',
    'Rock Chic (Da & Đinh tán) Mạnh Mẽ',
    'Preppy (Quý tộc học đường) Thanh Lịch',
    'Sustainable Fashion (Tái chế) Bảo Vệ Môi Trường',
    'Áo Dài Cách Tân Thời Trang (Modern Ao Dai)',
    'Trang Phục Dân Tộc Stylist (Ethnic Chic)',
    'Trang Phục Kim Loại (Metallic) Lấp Lánh',
    'Trang Phục Lông Vũ (Feather) Kiêu Sa',
    'Trang Phục Xuyên Thấu (Sheer) Gợi Cảm',
    'Trang Phục Oversize (Rộng thùng thình)',
    'Trang Phục Unisex (Phi giới tính)',
    'Trang Phục Color Block (Phối màu) Rực Rỡ',
    'Trang Phục Monogram (Họa tiết) Hàng Hiệu',
    'Trang Phục Denim on Denim (Jean) Bụi Bặm',
    'Trang Phục Safari (Thám hiểm) Năng Động',
    'Trang Phục Military (Quân đội) Cá Tính',
    'Trang Phục Sporty Chic (Thể thao) Khỏe Khoắn',
    'Trang Phục Lounge Wear (Đồ ngủ) Sang Chảnh',
    'Trang Phục Airport Style (Sân bay) Thoải Mái',
    'Trang Phục Office Siren (Thư ký) Quyến Rũ',
    'Trang Phục Balletcore (Vũ công) Nhẹ Nhàng',
    'Trang Phục Barbiecore (Màu hồng) Búp Bê',
    'Trang Phục Mermaidcore (Tiên cá) Lấp Lánh',
    'Trang Phục Fairycore (Tiên nữ) Rừng Xanh',
    'Trang Phục Gorpcore (Leo núi) Thực Dụng',
    'Trang Phục Normcore (Bình thường) Giản Dị',
    'Trang Phục Old Money (Giới siêu giàu) Kín Đáo',
    'Trang Phục Quiet Luxury (Sang trọng thầm lặng)',
    'Trang Phục Dopamine Dressing (Vui vẻ) Sặc Sỡ',
    'Trang Phục Tet Holiday (Lễ Tết) Đỏ Vàng'
];

export const FAMILY_STUDIO_VIP_CONCEPTS = [
    // --- 50+ VIP FAMILY STUDIO CONCEPTS (TET) ---
    'Đại Gia Đình Hoàng Tộc (Royal Family) Quý Phái',
    'Gia Đình Doanh Nhân Thành Đạt (CEO Family)',
    'Gia Đình Nghệ Sĩ Nổi Tiếng (Celebrity Family)',
    'Gia Đình Siêu Anh Hùng (Superhero Family) Giải Cứu',
    'Gia Đình Phép Thuật (Harry Potter) Pháp Sư',
    'Gia Đình Điệp Viên (Spy Family) Hành Động',
    'Gia Đình Thập Niên 70s (Retro Family) Sài Gòn',
    'Gia Đình Tương Lai (Futuristic Family) Robot',
    'Gia Đình Cổ Tích (Fairytale Family) Disney',
    'Gia Đình Trên Du Thuyền (Yacht Family) Sang Chảnh',
    'Gia Đình Mafia (Godfather) Bố Già',
    'Gia Đình Nông Dân Quý Tộc (Gentleman Farmer)',
    'Gia Đình Phi Hành Gia (Astronaut Family) NASA',
    'Gia Đình Rock Band (Rocker Family) Sôi Động',
    'Gia Đình Đầu Bếp (Masterchef Family) Vua Bếp',
    'Gia Đình Thể Thao (Olympic Family) Vận Động Viên',
    'Gia Đình Cắm Trại (Glamping Family) Chill',
    'Gia Đình Mặc Đồ Pijama (Pajama Party) Vui Nhộn',
    'Gia Đình Hóa Trang Táo Quân (Kitchen Gods)',
    'Gia Đình Giáng Sinh Ấm Áp (Christmas Family)',
    'Gia Đình Tết Truyền Thống Việt Nam (Ao Dai)',
    'Gia Đình Hàn Quốc (Hanbok Family) Dễ Thương',
    'Gia Đình Nhật Bản (Kimono Family) Trang Trọng',
    'Gia Đình Châu Âu Cổ Điển (European Family)',
    'Gia Đình Tỷ Phú (Succession Family) Quyền Lực',
    'Gia Đình Thợ Săn (Hunter Family) Rừng Rậm',
    'Gia Đình Họa Sĩ (Artist Family) Sáng Tạo',
    'Gia Đình Bác Sĩ (Doctor Family) Áo Blouse',
    'Gia Đình Giáo Sư (Professor Family) Trí Thức',
    'Gia Đình Cảnh Sát (Police Family) Uy Nghiêm',
    'Gia Đình Lính Cứu Hỏa (Firefighter Family)',
    'Gia Đình Phi Công (Pilot Family) Bầu Trời',
    'Gia Đình Thủy Thủ (Sailor Family) Đại Dương',
    'Gia Đình Xiếc (Circus Family) Vui Vẻ',
    'Gia Đình Ảo Thuật Gia (Magician Family) Bí Ẩn',
    'Gia Đình Vũ Công (Dancer Family) Uyển Chuyển',
    'Gia Đình Ca Sĩ (Singer Family) Ngôi Sao',
    'Gia Đình Diễn Viên (Actor Family) Điện Ảnh',
    'Gia Đình Người Mẫu (Model Family) Thời Trang',
    'Gia Đình Kiến Trúc Sư (Architect Family)',
    'Gia Đình Kỹ Sư (Engineer Family) Công Nghệ',
    'Gia Đình Lập Trình Viên (Coder Family) IT',
    'Gia Đình Streamer (Youtuber Family) Online',
    'Gia Đình Game Thủ (Gamer Family) E-sport',
    'Gia Đình Thám Tử (Detective Family) Sherlock',
    'Gia Đình Ma Cà Rồng (Vampire Family) Twilight',
    'Gia Đình Người Sói (Werewolf Family)',
    'Gia Đình Zombie (Walking Dead) Halloween',
    'Gia Đình Robot (Cyborg Family) AI',
    'Gia Đình Hạnh Phúc (Happy Family) Cười Tươi'
];

export const CALENDAR_WEEKDAYS = ['Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7', 'Chủ Nhật'];
export const CALENDAR_DAYS = Array.from({length: 31}, (_, i) => (i + 1).toString());
export const CALENDAR_MONTHS = Array.from({length: 12}, (_, i) => `Tháng ${i + 1}`);

export const TET_WISHES = [
    // --- 50+ VIP TET WISHES ---
    'VẠN SỰ NHƯ Ý',
    'TẤN TÀI TẤN LỘC',
    'AN KHANG THỊNH VƯỢNG',
    'CUNG CHÚC TÂN XUÂN',
    'XUÂN NHƯ Ý - TẾT AN KHANG',
    'TÀI LỘC ĐẦY NHÀ',
    'PHÚ QUÝ VINH HOA',
    'GIA ĐẠO BÌNH AN',
    'ĐẮC LỘC TOÀN GIA',
    'PHÚC LỘC THỌ TOÀN',
    'KHAI XUÂN ĐẠI CÁT',
    'MÃ ĐÁO THÀNH CÔNG',
    'XUÂN SANG ĐẮC LỘC',
    'TẾT ĐẾN AN VUI',
    'HẠNH PHÚC NGẬP TRÀN',
    'SỨC KHỎE DỒI DÀO',
    'LỘC BIẾC MAI VÀNG',
    'XUÂN AN KHANG',
    'TẾT SUM VẦY',
    'ĐẠI PHÚ ĐẠI QUÝ',
    'CÔNG THÀNH DANH TOẠI',
    'SỰ NGHIỆP THĂNG TIẾN',
    'TIỀN VÀO NHƯ NƯỚC',
    'LỘC ĐẾN QUANH NĂM',
    'GIA ĐÌNH HẠNH PHÚC',
    'CON CHÁU ĐÔNG ĐÚC',
    'HỌC HÀNH TẤN TỚI',
    'TÌNH DUYÊN PHƠI PHỚI',
    'MUA MAY BÁN ĐẮT',
    'VỮNG BƯỚC THÀNH CÔNG',
    'Ý CHÍ VỮNG VÀNG',
    'TÂM HỒN AN LẠC',
    'THÂN TÂM AN LẠC',
    'PHÚC NHƯ ĐÔNG HẢI',
    'THỌ TỶ NAM SƠN',
    'BÁCH NIÊN GIAI LÃO',
    'RỒNG PHƯỢNG SUM VẦY',
    'HOA KHAI PHÚ QUÝ',
    'TRÚC BÁO BÌNH AN',
    'CÁT TƯỜNG NHƯ Ý',
    'NGŨ PHÚC LÂM MÔN',
    'TAM DƯƠNG KHAI THÁI',
    'NHẤT BẢN VẠN LỢI',
    'THUẬN BUỒM XUÔI GIÓ',
    'THƯỢNG LỘ BÌNH AN',
    'VẠN SỰ HANH THÔNG',
    'TỶ SỰ NHƯ MƠ',
    'TRIỆU ĐIỀU BẤT NGỜ',
    'TẾT VUI TRỌN VẸN',
    'XUÂN MỚI BÌNH AN'
];

export const VIP_QUOTES = [
    "Tết đến rồi, đẹp lên thôi!",
    "Năm mới – diện mới – khí chất mới.",
    "Tết này em chọn… xinh xuất sắc.",
    "Tết không cần nhiều, chỉ cần ĐẸP.",
    "Xuân sang rồi, bung sắc liền!",
    "Tết có đôi, còn em có… ảnh đẹp.",
    "Lì xì đâu chưa thấy, chỉ thấy em hơi đẹp.",
    "Tết chill – em rực rỡ.",
    "Xuân này em hứa: ĐẸP ĐẾN PHÁT MÊ.",
    "Tết này icon chính là em.",
    "Mã đáo thành công rực rỡ",
    "Ngựa vàng mang lộc đầu năm",
    "Phi nhanh mở cửa thắng lớn",
    "Chiến mã bứt phá cả năm",
    "Mã khí thịnh vượng bùng nổ",
    "Cưỡi gió phi thẳng thành công",
    "Ngựa thần mở vận đại cát",
    "Tốc độ bùng nổ như ngựa",
    "Vận may phi nước đại tới",
    "Tiền tài tuôn như ngựa chạy"
];

// --- 100 POSES FOR FEMALE VIP ---
export const FEMALE_POSES_VIP = [
    // 1–25: KẾT HỢP ĐỨNG + TAY + CẢM XÚC
    "Đứng nghiêng 45° + tay che miệng + cười cute.",
    "Đứng xoay người + tay đưa ngang má + mắt nhắm nhẹ.",
    "Đứng vắt chân + hai tay tạo trái tim + nụ cười kute.",
    "Đứng pose chữ S + tay vuốt tóc + ánh mắt sexy.",
    "Hai tay chống hông + mắt nháy nhẹ + miệng cong gợi cảm.",
    "Đứng một chân nhón + tay che nắng + cười rạng rỡ.",
    "Đứng tạo dáng idol + tay chữ V + môi chu siêu dễ thương.",
    "Hai tay khoanh + ánh mắt quyến rũ lạnh lùng.",
    "Đứng chống cằm + body nghiêng + vibe shy girl.",
    "Đứng cắn môi + tay kéo áo nhẹ + vibe sexy.",
    "Một tay chống hông + tay còn lại đưa lên tóc + mắt nhìn lệch.",
    "Đứng xoay lưng + xoay đầu lại + biểu cảm gợi cảm.",
    "Đứng cúi đầu nhẹ + tay chạm môi + ánh mắt sâu.",
    "Đứng dang tay xoay váy + mặt cười tỏa nắng.",
    "Đứng kiểu model + tay cài tóc + gương mặt confident.",
    "Đứng kẹp tay áo + biểu cảm cute ngại ngùng.",
    "Đứng nhướn chân + tay nắm cổ áo + môi cong nhẹ.",
    "Đứng dựa tường + tay bỏ túi + ánh mắt quyến rũ.",
    "Tay chống lưng + ngực hơi đưa ra + pose sexy.",
    "Một tay giơ lên trời + một tay để hông + cười tinh nghịch.",
    "Đứng tay dang sang hai bên + mắt nhắm + vibe thiên thần.",
    "Đứng một chân co + tay chống cằm + cute.",
    "Đứng ôm gối chữ O bằng tay + môi cong dễ thương.",
    "Đứng kéo tóc hai bên + ánh mắt mèo con.",
    "Đứng xoay váy + chân chéo + tay dang nhẹ.",

    // 26–50: KẾT HỢP NGỒI + TAY CHÂN + CẢM XÚC
    "Ngồi bó gối + hai tay ôm chân + cười như trẻ con.",
    "Ngồi vắt chân + tay chống má + biểu cảm sexy nhẹ.",
    "Ngồi xoay người 45° + tay vuốt tóc + nhìn lệch quyến rũ.",
    "Ngồi ôm gối một tay + tay còn lại che miệng cute.",
    "Ngồi trên sàn + hai chân mở nhẹ + ánh mắt seductive.",
    "Ngồi tựa tường + tay ôm đầu gối + gương mặt shy girl.",
    "Ngồi dạng chân nhẹ + hai tay chống sau + ánh mắt tự tin.",
    "Ngồi trên ghế + một chân đặt cao + pose fashion.",
    "Ngồi dựa lưng + tay kéo tóc + môi cong.",
    "Ngồi tư thế “nàng thơ” + tay đặt hờ lên cổ.",
    "Ngồi bệt + tay chống xuống đất + mắt cười.",
    "Ngồi chéo chân + tay ôm gối + gương mặt đáng yêu.",
    "Ngồi xoay chèo người + tay vuốt đùi + sexy vibe.",
    "Ngồi ôm gối + cười nháy mắt siêu cute.",
    "Ngồi trên ghế xoay lưng ra trước + tay ôm khung ghế.",
    "Ngồi kiểu model runway + chân dài duỗi ra.",
    "Ngồi nghiêng + tay chống thái dương + mắt xa xăm.",
    "Ngồi kéo váy nhẹ + tay đặt lên đùi + vibe hấp dẫn.",
    "Ngồi chống cằm + mái tóc rơi sang một bên.",
    "Ngồi ngửa đầu ra sau + tay đặt lên cổ.",
    "Ngồi gập người ôm chân + nụ cười hạnh phúc.",
    "Ngồi xoay váy trên sàn + tay đưa ra trước.",
    "Ngồi pose yoga nhẹ + cười hiền.",
    "Ngồi nháy mắt + tay hình trái tim.",
    "Ngồi ôm chân + toàn thân nghiêng sexy.",

    // 51–75: KẾT HỢP NẰM + XOAY + BIỂU CẢM
    "Nằm nghiêng chống đầu + cười nhẹ.",
    "Nằm ngửa + tay đặt lên môi + ánh mắt long lanh.",
    "Nằm úp + xoay đầu + tóc xoã.",
    "Nằm ôm gối + môi chu cute.",
    "Nằm chống 1 khủy tay + pose sexy.",
    "Nằm nghiêng chân duỗi dài + tay đặt hờ lên eo.",
    "Nằm tạo dáng chữ S + mắt nhìn camera.",
    "Nằm nâng đầu + tay vuốt tóc + vibe tiểu thư.",
    "Nằm xoay lưng + đầu hòa vào tóc xoã.",
    "Nằm cuộn tròn như mèo + ánh mắt dễ thương.",
    "Nằm pose fashion editorial + đầu hơi vươn cao.",
    "Nằm ôm chăn + ánh mắt gợi tình.",
    "Nằm dạng tay hai bên + môi cong quyến rũ.",
    "Nằm nhắm mắt + tóc xõa + vibe công chúa.",
    "Nằm xoay chân nhẹ + tay đặt lên vai.",
    "Nằm úp 1 phần + ánh mắt muốn yêu.",
    "Nằm nghiêng đầu + tay che nửa mặt + sexy.",
    "Nằm quay đầu ra sau + tóc bung xoãi.",
    "Nằm pose dạng model tạp chí.",
    "Nằm tay ôm ngực + mắt sâu tình.",

    // 76–100: TƯ THẾ KHÓ + SEXY + NGHỆ THUẬT
    "Uốn cong người + tay đặt lên đùi + mắt quyến rũ.",
    "Tư thế dancer xoay người + tóc bung 8D.",
    "Nhảy giữa không trung + cười cute.",
    "Xoạc nhẹ + tay che mặt + ánh mắt gợi cảm.",
    "Tư thế bẻ lưng mềm dẻo + đôi tay dang.",
    "Chống 1 tay trên sàn + chân co + ánh mắt deep.",
    "Tư thế xoay váy tốc độ + nụ cười sáng.",
    "Pose yoga khó + tóc xoã gợi cảm.",
    "Tư thế fashion high-level + môi cong.",
    "Một chân nâng cao + tay chạm cổ + sexy.",
    "Tư thế quỳ gối + tay vuốt tóc + ánh mắt seductive.",
    "Tư thế quỳ + chống tay + lưng hơi cong.",
    "Tư thế ngồi squat + cười cute.",
    "Tư thế xoay hông kiểu dancer.",
    "Tư thế pose “thiên thần” dang tay.",
    "Tư thế hair flip – tung tóc.",
    "Tư thế quỳ gối fashion editorial.",
    "Tư thế nằm nửa người uốn cong.",
    "Tư thế tạo đường cong cơ thể chữ S.",
    "Tư thế duỗi chân dài + tay nâng cằm.",
    "Tư thế quỳ quay lưng + xoay đầu lại.",
    "Tư thế uốn lưng cầu vồng + ánh mắt sexy.",
    "Pose xoay hình chữ V bằng tay.",
    "Tư thế gập người nửa thân + mắt nhìn camera.",
    "Tư thế xoay chân phức tạp + tay vuốt tóc + biểu cảm quyến rũ."
];

// --- 100 POSES FOR MALE VIP ---
export const MALE_POSES_VIP = [
    // 1–30: TƯ THẾ ĐỨNG – QUYỀN LỰC – LỊCH LÃM – DOANH NHÂN TỶ ĐÔ
    "Đứng thẳng vai rộng + tay đút túi + nhìn xa phong độ.",
    "Đứng khoanh tay + ánh mắt sắc lạnh CEO.",
    "Đứng chống hông + hơi nghiêng người đầy tự tin.",
    "Đứng dựa tường + tay vuốt tóc + ánh mắt quyến rũ.",
    "Đứng thẳng + một tay kéo cổ áo vest.",
    "Đứng bắt chéo chân + tay cài khuy áo.",
    "Đứng xoay người 45° + nhìn qua vai đỉnh cao.",
    "Đứng bỏ một tay trong túi quần + tay còn lại cầm kính.",
    "Đứng cắn môi nhẹ + ánh mắt deep.",
    "Đứng kẹp áo khoác lên vai + thần thái doanh nhân.",
    "Đứng với hai tay chống sau lưng + khí chất quý ông.",
    "Đứng tay cầm điện thoại nhìn xuống sang trọng.",
    "Đứng tay kẹp cà vạt + thần thái điển trai.",
    "Đứng chống tay lên tường + nhìn sát camera.",
    "Đứng nhìn xuống đất + biểu cảm lạnh lùng.",
    "Đứng một chân nhón nhẹ + tay chống cằm deep.",
    "Đứng xoay đầu qua bên + hai tay thả lỏng.",
    "Đứng khoanh tay trước ngực + ánh mắt quyền lực.",
    "Đứng dang nhẹ hai chân + dáng phong độ.",
    "Đứng dạng chân mạnh mẽ + ánh mắt “alpha male”.",
    "Đứng hai tay bỏ hai túi + dáng relaxed luxury.",
    "Đứng cầm áo vest trên vai + nụ cười nhẹ.",
    "Đứng hai tay chống hông + camera low-angle.",
    "Đứng dang 1 tay ra sau + nụ cười phong trần.",
    "Đứng xoay người + cầm ly rượu vang sang trọng.",
    "Đứng một tay chống tường + ánh mắt quyến rũ.",
    "Đứng gập người buộc dây giày + góc nghiêng đẹp trai.",
    "Đứng hai tay nắm cổ áo + ánh mắt self-made billionaire.",
    "Đứng giơ một tay lên trời + khí chất vĩ mô.",
    "Đứng nghiêng + túm tay áo sơ mi đang xắn.",

    // 31–60: TƯ THẾ NGỒI – SANG – PHONG ĐỘ – QUYỀN LỰC
    "Ngồi thẳng lưng + khoanh tay + ánh mắt quyền lực.",
    "Ngồi bắt chéo chân + tay đặt lên đùi.",
    "Ngồi nghiêng 45° + tay chống cằm thoughtful.",
    "Ngồi trên sofa + tay khoác lên lưng ghế.",
    "Ngồi cúi đầu + xắn tay áo sơ mi mạnh mẽ.",
    "Ngồi xoay người + tay giữ cổ áo vest.",
    "Ngồi chống 1 tay lên bàn + ánh mắt lạnh.",
    "Ngồi chân mở nhẹ + tay thả lỏng.",
    "Ngồi với 1 chân bắt chéo lên gối + nét quý ông.",
    "Ngồi ngả người ra sau tự tin.",
    "Ngồi kiểu CEO, tay đan vào nhau.",
    "Ngồi cúi mặt + đeo kính + ánh sáng mạnh.",
    "Ngồi một chân co, một chân duỗi + thần thái lịch lãm.",
    "Ngồi kiểu fashion model high-end.",
    "Ngồi với tay vuốt tóc + ánh mắt sexy.",
    "Ngồi xoay ghế ngược + tay đặt lên lưng ghế.",
    "Ngồi tựa đầu vào tay + nụ cười nửa miệng.",
    "Ngồi chống 2 tay lên bàn + thần thái tập trung.",
    "Ngồi xoay mặt ra ánh sáng + đôi mắt sâu.",
    "Ngồi gác chân lên ghế + dáng nghệ sĩ giàu sang.",
    "Ngồi vắt chân + tay cầm ly cà phê sang trọng.",
    "Ngồi khoanh tay – chân mở – CEO.",
    "Ngồi xoay vai ra sau + khí chất quý ông lạnh lùng.",
    "Ngồi tư thế thư giãn + ánh mắt lãng tử.",
    "Ngồi cúi nhẹ người về phía camera.",
    "Ngồi gập người cột dây giày + dáng menly.",
    "Ngồi pose studio + ánh sáng bóng đổ đẹp.",
    "Ngồi với áo khoác đặt trên vai.",
    "Ngồi ghế cao bar + xoay vai qua lại.",
    "Ngồi kết hợp mặt lạnh + đôi môi cong nhẹ.",

    // 61–80: TƯ THẾ NẰM – PHONG LƯU – LỊCH LÃM – QUYẾN RŨ
    "Nằm nghiêng + tay chống đầu + mắt nhìn xa.",
    "Nằm úp nhẹ + xoay đầu nhìn camera.",
    "Nằm ngửa + tay đặt lên ngực + ánh mắt deep.",
    "Nằm co 1 chân + gương mặt thư thái.",
    "Nằm hơi xoay người + tay vuốt tóc.",
    "Nằm nghiêng + ánh mắt quyến rũ kiểu điện ảnh.",
    "Nằm fashion editorial – tạo đường cong nam tính.",
    "Nằm ở sofa + tay để sau đầu + pose relaxed luxury.",
    "Nằm tay ôm gối + biểu cảm suy tư.",
    "Nằm xoay đầu + tay chạm môi nhẹ.",
    "Nằm pose “bad boy” với ánh mắt sấm sét.",
    "Nằm dang 2 tay + mắt nhìn trần – deep mood.",
    "Nằm 1 tay trước bụng + dáng phong trần.",
    "Nằm nghiêng kiểu người mẫu nước ngoài.",
    "Nằm dạng rộng + nhìn mạnh mẽ.",
    "Nằm đọc sách + góc nghiêng thần thánh.",
    "Nằm trên bãi cỏ + tay che nắng.",
    "Nằm ngả người + tay cầm điện thoại luxury.",
    "Nằm mắt nhắm + tóc hơi rũ.",
    "Nằm sấp nhẹ + cơ thể lộ đường nét nam tính.",

    // 81–100: TƯ THẾ KHÓ – HIGH-FASHION – SIÊU ĐẲNG CẤP
    "Tư thế xoay người mạnh + tóc bay.",
    "Quỳ 1 chân + tay chống đầu gối + ánh mắt lãnh đạm.",
    "Nhảy nhẹ mid-air + camera freeze.",
    "Cúi người 90° + pose fashion runway.",
    "Xoay cổ tay + mặt nghiêng + ánh mắt sắc.",
    "Chống 1 tay lên tường + chân dạng chuẩn model.",
    "Đang đeo đồng hồ + pose góc sang.",
    "Uốn lưng nhẹ + ánh sáng rọi một bên.",
    "Ngửa đầu ra sau + tay nắm cổ áo.",
    "Pose đường cong chữ S phiên bản nam.",
    "Bước đi mạnh mẽ + tay đưa ra sau. ",
    "Quay đầu nhìn lại khi đang bước.",
    "Một tay đưa lên trán + ánh mắt deep mysterious.",
    "Tay cầm áo vest tung nhẹ ra sau.",
    "Dang tay kiểu artist high-class.",
    "Bước chân dài kiểu model quốc tế.",
    "Tư thế đứng lùi + gương mặt lạnh lùng.",
    "Ngồi quỳ thấp + tay chống sàn + ánh mắt sắc.",
    "Tư thế fashion editorial kiểu GQ Men.",
    "Tư thế xoay mình kết hợp áo bay + khí chất siêu cấp."
];

export const CALENDAR_TYPES = [
    '📅 Lịch Tờ Từng Tháng (Layout 1 Tháng - Focus Chi Tiết)',
    '📆 Lịch Nguyên Năm (Full Year Poster - Overview)',
    '📒 Lịch Để Bàn (Desk Calendar - Office Style)',
    '📜 Lịch Bloc Treo Tường (Traditional Bloc)',
    '📱 Hình Nền Điện Thoại (Lockscreen Calendar)'
];

export const CALENDAR_YEARS = [
    'Năm 2026 (Bính Ngọ)'
];

export const CALENDAR_CONCEPTS = [
    // --- 50+ VIP CALENDAR CONCEPTS (TET) ---
    '📅 1. Lịch Sang Trọng Đen – Gold Modern Luxury',
    '📅 2. Lịch City Luxury – Doanh Nhân Tỷ Đô',
    '📅 3. Lịch Tết Cổ Điển Sang – Gỗ & Gold',
    '📅 4. Lịch Minimal Đỉnh Cao – Vàng Trắng 8K',
    '📅 5. Lịch Studio 8K – Lụa Vàng Bay Cao Cấp',
    '📅 6. Lịch Neon Gold Future – Công Nghệ',
    '📅 7. Lịch Richlife – Vàng & Trắng Cao Cấp',
    '📅 8. Lịch Ngọ Vàng – Premium Metallic',
    '📅 9. Lịch Fashion Tết – Sàn Diễn Cao Cấp',
    '📅 10. Lịch Tết Nghệ Thuật – Background 3D',
    '📅 11. Lịch Grid 4x3 (12 Ô Siêu Chuẩn)',
    '📅 12. Lịch Grid 3x4 (Ngang Rộng)',
    '📅 13. Lịch 12 Tháng Ngang (1 Hàng Dài)',
    '📅 14. Lịch 2 Hàng (Cân Đối Hoàn Hảo)',
    '📅 15. Lịch 12 Card Mini (Premium)',
    '📅 16. Lịch Hình Tròn (Hiện Đại)',
    '📅 17. Lịch Block Truyền Thống (Đỏ Vàng)',
    '📅 18. Lịch Thanh Bar Mảnh (Siêu Hiện Đại)',
    '📅 19. Lịch 3D Nổi (Sắc Xảo Đẳng Cấp)',
    '📅 20. Lịch Đồng Tâm (12 Cung Tròn)',
    '📅 21. Lịch Lục Giác (Ong) Tổ Hợp',
    '📅 22. Lịch Tam Giác (Kim Tự Tháp)',
    '📅 23. Lịch Xoắn Ốc (Vô Cực)',
    '📅 24. Lịch Bậc Thang (Thăng Tiến)',
    '📅 25. Lịch Cây Đào (Hoa Nở 12 Tháng)',
    '📅 26. Lịch 12 Con Giáp (Zodiac Art)',
    '📅 27. Lịch Phong Thủy (Ngũ Hành)',
    '📅 28. Lịch Thư Pháp (Calligraphy)',
    '📅 29. Lịch Tranh Đông Hồ (Folk Art)',
    '📅 30. Lịch Sơn Mài (Lacquer) Sang Trọng',
    '📅 31. Lịch Lụa Tơ Tằm (Silk)',
    '📅 32. Lịch Gỗ Khắc Laser (Wood)',
    '📅 33. Lịch Đá Quý (Gemstone)',
    '📅 34. Lịch Kim Loại (Metal) Vàng Đồng',
    '📅 35. Lịch Kính Cường Lực (Glass)',
    '📅 36. Lịch Đèn Led (Neon Light)',
    '📅 37. Lịch Đồng Hồ (Clock) Tích Hợp',
    '📅 38. Lịch Gương (Mirror) Soi',
    '📅 39. Lịch Nam Châm (Magnet) Tủ Lạnh',
    '📅 40. Lịch Xé (Tear-off) Hàng Ngày',
    '📅 41. Lịch Để Bàn Chữ A',
    '📅 42. Lịch Để Bàn Chữ M',
    '📅 43. Lịch Treo Tường Lò Xo',
    '📅 44. Lịch Treo Tường Nẹp Thiếc',
    '📅 45. Lịch Bỏ Túi (Pocket) Mini',
    '📅 46. Lịch Poster Khổ Lớn',
    '📅 47. Lịch Sticker (Dán) Vui Nhộn',
    '📅 48. Lịch Tô Màu (Coloring) Sáng Tạo',
    '📅 49. Lịch Ảnh Gia Đình (Family Photo)',
    '📅 50. Lịch Doanh Nghiệp (Corporate)'
];

export const PHOENIX_CONCEPTS = [
    // --- 50+ VIP PHOENIX CONCEPTS (TET) ---
    '🔥 Phượng Hoàng Tái Sinh (Resurrection Phoenix) Từ Tro Tàn',
    '🔥 Nữ Hoàng Lửa Thiêng (Fire Queen) Đội Vương Miện Lửa',
    '🔥 Vũ Khúc Lửa Thần (Fire Dance) Múa Quạt Lửa',
    '🔥 Cung Điện Mặt Trời (Sun Palace) Vàng Rực',
    '🔥 Chiến Binh Phượng Hoàng (Phoenix Warrior) Giáp Vàng',
    '🔥 Lễ Hội Lửa Thiêng (Sacred Fire Festival) Đêm Giao Thừa',
    '🔥 Cổng Trời Rực Lửa (Burning Heaven Gate) Khai Xuân',
    '🔥 Phượng Hoàng Song Sinh (Twin Phoenix) Cân Bằng Âm Dương',
    '🔥 Ngai Vàng Lửa Đỏ (Throne of Fire) Quyền Lực',
    '🔥 Thảm Đỏ Hoàng Gia (Royal Red Carpet) Pháo Hoa Vàng',
    '🔥 Đôi Cánh Lửa Neon (Neon Fire Wings) Cyberpunk Tết',
    '🔥 Trứng Phượng Hoàng (Phoenix Egg) Nở Ra Tài Lộc',
    '🔥 Hoa Đăng Lửa (Floating Fire Lanterns) Thả Sông',
    '🔥 Kim Thân Bất Hoại (Golden Skin) Mình Đồng Da Sắt',
    '🔥 Mắt Phượng Hoàng (Phoenix Eye Makeup) Sắc Sảo',
    '🔥 Lụa Đỏ Cháy (Burning Silk) Bay Trong Gió',
    '🔥 Hoa Ưu Đàm Lửa (Fire Udumbara Flower) Nở Rộ',
    '🔥 Thần Mặt Trời (Sun God) Ban Ánh Sáng',
    '🔥 Hỏa Diệm Sơn (Volcano Aesthetic) Nham Thạch',
    '🔥 Vòng Tròn Lửa Magic (Magic Fire Circle) Triệu Hồi',
    '🔥 Phượng Hoàng Băng Lửa (Ice & Fire Contrast) Đối Lập',
    '🔥 Cây Cổ Thụ Lửa (Burning Tree) Lá Vàng Rơi',
    '🔥 Mưa Tàn Tro Vàng (Golden Ash Rain) Lấp Lánh',
    '🔥 Xích Đu Lửa (Swing in Fire Ocean) Giữa Biển Lửa',
    '🔥 Cầu Lửa Bắc Ngang Trời (Fire Bridge) Nối Nhịp',
    '🔥 Lồng Đèn Kéo Quân Lửa (Spinning Lantern) Xoay Tròn',
    '🔥 Trống Trận Rực Lửa (Burning War Drums) Hào Hùng',
    '🔥 Quạt Giấy Khổng Lồ (Giant Phoenix Fan) Che Trời',
    '🔥 Phượng Hoàng Gấm Vóc (Embroidered Phoenix) Thêu Tay',
    '🔥 Tiên Nữ Hỏa Cung (Fire Fairy) Xinh Đẹp',
    '🔥 Hoàng Tử Lửa (Prince of Fire) Điển Trai',
    '🔥 Bếp Lửa Thần (Magical Kitchen Fire) Nấu Bánh Chưng',
    '🔥 Lân Sư Rồng Lửa (Fire Lion Dance) Múa Lửa',
    '🔥 Mặt Nạ Phượng Hoàng (Phoenix Mask) Bí Ẩn',
    '🔥 Cung Tên Lửa (Fire Bow & Arrow) Bắn Trúng Tim',
    '🔥 Đàn Tỳ Bà Lửa (Burning Pipa) Giai Điệu',
    '🔥 Hồ Sen Lửa (Red Lotus Fire) Rực Cháy',
    '🔥 Kim Tự Tháp Lửa (Fire Pyramid) Ai Cập',
    '🔥 Sao Hỏa Tết (Mars Tet Celebration) Vũ Trụ',
    '🔥 Dây Pháo Khổng Lồ (Giant Firecracker) Nổ Vang',
    '🔥 Thư Pháp Lửa (Fire Calligraphy) Nét Rồng',
    '🔥 Rượu Vang Lửa (Flaming Wine) Bốc Cháy',
    '🔥 Nhẫn Phượng Hoàng (Phoenix Ring Prop) Đính Đá',
    '🔥 Vườn Hồng Lửa (Burning Roses) Gai Góc',
    '🔥 Kim Cương Đỏ (Red Diamond Rain) Mưa Đá Quý',
    '🔥 Lụa Tân Cương (Xinjiang Fire Dance) Múa Lụa',
    '🔥 Phượng Hoàng Origami (Paper Phoenix) Giấy Gấp',
    '🔥 Gương Thần Lửa (Fire Mirror) Soi Bóng',
    '🔥 Bánh Xe Lửa (Wheel of Fire) Luân Hồi',
    '🔥 Pháo Hoa Đại Cảnh (Grand Firework Display) Rực Trời'
];

export const FLOWER_SPRING_CONCEPTS = [
    // --- 50+ VIP VIETNAM FLOWER SPRING CONCEPTS ---
    '🌸 Lạc Bước Tại Vườn Đào Nhật Tân (Hà Nội) Rực Rỡ',
    '🌼 Thả Dáng Bên Vườn Mai Vàng Bến Tre Rực Nắng',
    '🌷 Check-in Cánh Đồng Tulip Bà Nà Hills (Đà Nẵng)',
    '💠 Mơ Màng Giữa Vườn Cẩm Tú Cầu Đà Lạt Sương Sớm',
    '💮 Chụp Ảnh Tại Thung Lũng Mận Trắng Mộc Châu (Sơn La)',
    '🌸 Dạo Bước Dưới Rừng Hoa Anh Đào Sapa Mờ Sương',
    '🌾 Tạo Dáng Bên Cánh Đồng Hoa Cải Vàng Ninh Bình',
    '🌺 Rực Rỡ Sắc Màu Tại Làng Hoa Sa Đéc (Đồng Tháp)',
    '🏵️ Du Xuân Vườn Hoa Thành Phố Đà Lạt (City Garden)',
    '🪷 Tĩnh Lặng Bên Hồ Sen Tinh Khiết Chùa Hương',
    '🌸 Thiếu Nữ Bên Gốc Đào Phai Cổ Thụ Nghìn Năm',
    '🌼 Áo Dài Thướt Tha Giữa Rừng Hoa Dã Quỳ Ba Vì',
    '🌻 Tỏa Sáng Tại Cánh Đồng Hướng Dương Nghệ An',
    '🌿 Chụp Ảnh Nghệ Thuật Tại Đồi Chè Trái Tim Mộc Châu',
    '🌺 Check-in Đường Hoa Nguyễn Huệ (Sài Gòn) Ngày Tết',
    '🌸 Mộng Mơ Bên Suối Hoa Đào Y Tý (Lào Cai)',
    '💮 Lãng Mạn Tại Rừng Hoa Ban Trắng Điện Biên',
    '🌼 Rực Rỡ Bên Vườn Cúc Mâm Xôi Hưng Yên',
    '🌷 Sang Chảnh Tại Vườn Hoa Châu Âu Vinpearl Nha Trang',
    '🌸 Dịu Dàng Bên Hoa Tam Giác Mạch Hà Giang',
    '🌺 Tạo Dáng Bên Giàn Hoa Giấy Hội An Cổ Kính',
    '🏵️ Chụp Ảnh Cùng Xe Hoa Mùa Xuân Trên Phố Phan Đình Phùng',
    '🌿 Du Xuân Vườn Quốc Gia Cúc Phương Mùa Bướm',
    '🌸 Thả Dáng Bên Hoa Đỗ Quyên Đỉnh Fansipan',
    '🌼 Ngắm Hoa Cải Trắng Tại Đơn Dương (Lâm Đồng)',
    '🌺 Rực Lửa Bên Hàng Phượng Tím Đà Lạt',
    '🌸 Chụp Ảnh Tại Chợ Hoa Hàng Lược (Phố Cổ Hà Nội)',
    '💠 Lạc Vào Rừng Hoa Sim Tím Phú Quốc',
    '🌻 Tạo Dáng Bên Cánh Đồng Hoa Mặt Trời Ecopark',
    '💮 Tinh Khôi Bên Vườn Hoa Loa Kèn Tháng 4',
    '🌸 Check-in Vườn Đào Chuông Bà Nà Núi Chúa',
    '🌺 Quyến Rũ Bên Rừng Hoa Gạo Đỏ (Mộc Miên) Bắc Giang',
    '🌼 Dạo Chơi Vườn Hoa Bãi Đá Sông Hồng',
    '🌷 Chụp Ảnh Concept Nàng Thơ Tại Thảo Nguyên Hoa Long Biên',
    '🌸 Mặc Cổ Phục Chụp Tại Vườn Đào Thất Thốn',
    '🌺 Tạo Dáng Bên Hồ Súng Tím Đồng Tháp Mười',
    '🏵️ Rực Rỡ Bên Con Đường Hoa Mười Giờ Tiền Giang',
    '🌸 Thưởng Ngoạn Hoa Tớ Dày Mù Cang Chải',
    '🌿 Chụp Ảnh Tại Làng Hoa Kiểng Cái Mơn (Chợ Lách)',
    '🌺 Duyên Dáng Bên Hoa Hải Đường Đỏ Thắm',
    '🌸 Ngắm Hoa Mai Anh Đào Tại Hồ Tuyền Lâm',
    '🌼 Tạo Dáng Bên Gánh Hàng Hoa Cúc Họa Mi',
    '🌷 Chụp Ảnh Tại Vườn Hoa Mãn Đình Hồng (Tiền Giang)',
    '🌸 Check-in Cây Cô Đơn Hồ Suối Vàng (Kèm Hoa)',
    '🌺 Dạo Bước Giữa Rừng Hoa Tràm Trà Sư (An Giang)',
    '💮 Tinh Tế Bên Bình Hoa Ly Tết Trong Biệt Thự',
    '🌸 Chụp Ảnh Macro Bên Nụ Tầm Xuân Đang Nở',
    '🌼 Thả Dáng Bên Thuyền Hoa Chợ Nổi Cái Răng',
    '🌺 Nổi Bật Giữa Vườn Hoa Trạng Nguyên Đỏ Rực',
    '🌸 Concept Tiên Nữ Giữa Rừng Hoa Mơ Hương Sơn'
];

export const PAGODA_LUCK_CONCEPTS = [
    // --- 50+ VIP PAGODA & LUCK CONCEPTS ---
    '🙏 Thành Tâm Dâng Hương Tại Chùa Bái Đính (Ninh Bình)',
    '🕍 Vãn Cảnh Chùa Tam Chúc (Hà Nam) Non Nước Hữu Tình',
    '🙏 Xin Xăm Đầu Năm Tại Lăng Ông Bà Chiểu (Sài Gòn)',
    '🏮 Thả Đèn Hoa Đăng Cầu May Tại Chùa Pháp Hoa',
    '🙏 Chắp Tay Cầu Nguyện Tại Đỉnh Thiêng Yên Tử (Quảng Ninh)',
    '⛩️ Đi Lễ Chùa Hương (Hà Nội) Ngồi Thuyền Suối Yến',
    '🙏 Hái Lộc Đầu Xuân Tại Chùa Một Cột (Biểu Tượng)',
    '🕍 Chụp Ảnh Áo Dài Tại Chùa Thiên Mụ (Huế) Cổ Kính',
    '🙏 Dâng Lễ Tại Miếu Bà Chúa Xứ (Châu Đốc - An Giang)',
    '🏮 Cầu Duyên Tại Chùa Hà (Hà Nội) Linh Thiêng',
    '🙏 Thiền Tịnh Tại Thiền Viện Trúc Lâm (Đà Lạt)',
    '🕍 Chiêm Bái Tượng Phật Bà Tây Bổ Đà Sơn (Tây Ninh)',
    '🙏 Xin Chữ Ông Đồ Tại Văn Miếu Quốc Tử Giám',
    '📿 Cầm Chuỗi Hạt Niệm Phật Tại Chùa Linh Ứng (Đà Nẵng)',
    '🙏 Lễ Phật Đầu Năm Tại Chùa Hoằng Pháp (Hóc Môn)',
    '🕍 Chụp Ảnh Nghệ Thuật Tại Chùa Bửu Long (Chùa Thái)',
    '🙏 Dâng Hoa Cúng Phật Tại Chùa Vĩnh Nghiêm (Sài Gòn)',
    '🏮 Đi Chùa Cầu An Đêm Giao Thừa Tại Chùa Phúc Khánh',
    '🙏 Chắp Tay Trước Tượng Phật Niết Bàn (Tà Cú)',
    '🕍 Vãn Cảnh Chùa Keo (Thái Bình) Kiến Trúc Cổ',
    '🙏 Rước Lộc Về Nhà Từ Đền Trần (Nam Định)',
    '🪷 Thả Cá Phóng Sinh Tại Hồ Tây (Phủ Tây Hồ)',
    '🙏 Cầu Tài Lộc Tại Đền Bà Chúa Kho (Bắc Ninh)',
    '🕍 Check-in Cổng Trời Chùa Linh Quy Pháp Ấn (Bảo Lộc)',
    '🙏 Lễ Phật Ngọc Xá Lợi Tại Chùa Quán Sứ',
    '🏮 Dạo Bước Sân Chùa Trấn Quốc (Hồ Tây) Chiều Tà',
    '🙏 Quay Kinh Luân Tại Chùa Tây Tạng (Bình Dương)',
    '🕍 Chụp Ảnh Cùng Tượng Phật Lớn Nhất Đông Nam Á',
    '🙏 Thành Kính Dâng Sao Giải Hạn Đầu Năm',
    '🌿 Hái Cành Lộc Non (Tượng Trưng) Cầu May Mắn',
    '🙏 Đi Lễ Đền Hùng (Phú Thọ) Nhớ Ơn Tổ Tiên',
    '🕍 Vãn Cảnh Chùa Dâu (Bắc Ninh) Cổ Nhất Việt Nam',
    '🙏 Cầu Bình An Tại Tượng Chúa Kito Vua (Vũng Tàu)',
    '🏮 Chụp Ảnh Áo Dài Lam Đi Chùa Đầu Năm',
    '🙏 Ngồi Thiền Dưới Gốc Bồ Đề Tâm Tĩnh Lặng',
    '🕍 Check-in Tháp Xá Lợi Chùa Phổ Minh',
    '🙏 Dâng Hương Tại Đền Ngọc Sơn (Cầu Thê Húc)',
    '📿 Cầm Quẻ Xăm May Mắn Đầu Năm Mới',
    '🙏 Lễ Chùa Hang (An Giang) Huyền Bí',
    '🕍 Chụp Ảnh Tại Chùa Cầu (Hội An) Di Sản',
    '🙏 Cầu Nguyện Tại Nhà Thờ Đá Sapa (Sương Mù)',
    '🏮 Treo Thẻ Ước Nguyện Lên Cây Cổ Thụ',
    '🙏 Đảnh Lễ Trước Tượng Quan Âm Nam Hải (Bạc Liêu)',
    '🕍 Vãn Cảnh Chùa Xiêm Cán (Khmer - Sóc Trăng)',
    '🙏 Đi Lễ Phủ Giầy (Nam Định) Mẫu Liễu Hạnh',
    '🌿 Cầm Cành Đào Nhỏ Đi Lễ Chùa (Du Xuân)',
    '🙏 Chụp Ảnh Góc Nghiêng Thần Thánh Khi Đang Khấn',
    '🕍 Check-in Tượng Phật Di Lặc Trên Đỉnh Cấm Sơn',
    '🙏 Cầu Nguyện Dưới Ánh Nắng Xuyên Qua Mái Chùa',
    '🏮 Cầm Đèn Lồng Đỏ Đứng Trước Cổng Tam Quan'
];

